### ISSUE TITLE
no such file or directory '../package.yaml'

### ISSUE THREAD

**Issue by rlidwka** [rlidwka/sinopia#1]
```javascript
Error: ENOENT, no such file or directory '../package.yaml'
    at Object.fs.openSync (fs.js:427:18)
    at Object.fs.readFileSync (fs.js:284:15)
    at Object.<anonymous> (/home/alex/applications/sinopia/node_modules/sinopia/bin/sinopia:6:28)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:901:3
```

**Comment by rlidwka** [comment]
I don't remember what that is anymore. Closing...
