### ISSUE TITLE
npm adduser fails with 400 against sinopia

### ISSUE THREAD

**Issue by saravanak** [rlidwka/sinopia#108]
I am having the following versions: 

```
$ sinopia --version
0.9.1
$ npm --version
1.4.3
$ node --version
v0.10.26
```

Now, `npm config ls` shows the following as documented in the `README`:

```
; cli configs
registry = "http://localhost:4873/"

; userconfig /Users/xxx/.npmrc
registry = "http://localhost:4873/"

; builtin config undefined
prefix = "/usr/local"
```

When trying to do `npm adduser` against the `admin` user provided by sinopia server running on my machine,  I get the following error:

```
Username: admin
Password:
Email: (this IS public) ad@d.com
npm http PUT http://localhost:4873/-/user/org.couchdb.user:admin
npm http 400 http://localhost:4873/-/user/org.couchdb.user:admin
npm ERR! Error: user/password is not found in request (npm issue?) : -/user/org.couchdb.user:admin
npm ERR!     at RegClient.<anonymous> (/usr/local/Cellar/node/0.10.26/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:237:14)
npm ERR!     at Request.self.callback (/usr/local/Cellar/node/0.10.26/lib/node_modules/npm/node_modules/request/request.js:123:22)
npm ERR!     at Request.EventEmitter.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/usr/local/Cellar/node/0.10.26/lib/node_modules/npm/node_modules/request/request.js:893:14)
npm ERR!     at Request.EventEmitter.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/usr/local/Cellar/node/0.10.26/lib/node_modules/npm/node_modules/request/request.js:844:12)
npm ERR!     at IncomingMessage.EventEmitter.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:920:16
npm ERR!     at process._tickCallback (node.js:415:13)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>
```

The sinopia server spits out a `400`:

```
http  <-- 400, user: undefined, req: 'PUT /-/user/org.couchdb.user:admin', error: user/password is not found in request (npm issue?)
```

Could someone please help me to resolve/debug this issue?

**Comment by lengziyu** [comment]
I had the same today with `npm@2.15.9` on Linux. Reproduce this error.
