### ISSUE TITLE
docker stops immediately

### ISSUE THREAD

**Issue by NezumiRyu** [rlidwka/sinopia#199]
/# docker run -d -p 4873:4873 keyvanfatehi/sinopia:latest
a48e2cc4809456e1f62a094506495903157e3529071f7ec156285a035b959b2f
/# docker logs a48e2cc4809456e1f62a094506495903157e3529071f7ec156285a035b959b2f

module.js:340
    throw err;
          ^
Error: Cannot find module 'sinopia/lib/config_gen'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/opt/sinopia/config_gen.js:2:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
sed: can't read /tmp/config.yaml: No such file or directory
 warn  --- config file  - /opt/sinopia/config.yaml

/opt/sinopia/node_modules/sinopia/lib/cli.js:75
  if (!config.user_agent) config.user_agent = 'Sinopia/'+pkg.version
             ^
TypeError: Cannot read property 'user_agent' of undefined
    at afterConfigLoad (/opt/sinopia/node_modules/sinopia/lib/cli.js:75:14)
    at Object.<anonymous> (/opt/sinopia/node_modules/sinopia/lib/cli.js:58:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/opt/sinopia/node_modules/sinopia/bin/sinopia:3:1)
    at Module._compile (module.js:456:26)

**Comment by rlidwka** [comment]
// cc: @keyvanfatehi

**Comment by keyvanfatehi** [comment]
@NezumiRyu the docker-sinopia image has recently been modified by popular demand to track the latest npm release (rather than tagging at specific releases). this is not an issue with sinopia, but with the docker image, please make the issue there https://github.com/keyvanfatehi/docker-sinopia/issues so the guys helping out with that can take a look.

i later want to go back and set up proper CI that tracks, tests, and tags docker image release, but it doesn't work this way currently.
