### ISSUE TITLE
publishing packages with namespaces does not work

### ISSUE THREAD

**Issue by fiws** [rlidwka/sinopia#202]
Hi,

publishing a package with a namespace like `@fiws/test` does not work for me.

I get these logs ( I replaced my domain with example.com):

## client

```
29 http request PUT https://npm.example.com/@fiws%2ftest
30 http 404 https://npm.example.com/@fiws%2ftest
31 verbose bad json Cannot PUT /@fiws/test
32 error registry error parsing json
33 verbose headers { server: 'nginx/1.6.2',
33 verbose headers   date: 'Mon, 09 Feb 2015 15:10:24 GMT',
33 verbose headers   'content-type': 'text/html; charset=utf-8',
33 verbose headers   'transfer-encoding': 'chunked',
33 verbose headers   connection: 'keep-alive',
33 verbose headers   'x-powered-by': 'Sinopia/1.0.0',
33 verbose headers   'x-frame-options': 'deny',
33 verbose headers   'x-content-type-options': 'nosniff',
33 verbose headers   vary: 'Accept-Encoding',
33 verbose headers   'x-status-cat': 'http://flic.kr/p/aV6juR',
33 verbose headers   'content-encoding': 'gzip' }
34 verbose request invalidating /home/fiws/.npm/npm.example.com/_40fiws_252ftest on PUT
35 error publish Failed PUT 404
36 verbose type unexpected_token
37 verbose stack SyntaxError: Unexpected token C
37 verbose stack Cannot PUT /@fiws/test
37 verbose stack
37 verbose stack     at Object.parse (native)
37 verbose stack     at CachingRegistryClient.<anonymous> (/home/fiws/npm/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:205:23)
37 verbose stack     at /home/fiws/npm/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:184:7
37 verbose stack     at Gunzip.onEnd (zlib.js:167:5)
37 verbose stack     at Gunzip.emit (events.js:117:20)
37 verbose stack     at _stream_readable.js:944:16
37 verbose stack     at process._tickCallback (node.js:442:13)
38 verbose cwd /tmp/test
39 error Linux 3.18.6-1-ARCH
40 error argv "node" "/home/fiws/npm/bin/npm" "publish"
41 error node v0.10.36
42 error npm  v2.5.0
43 error Unexpected token C
43 error Cannot PUT /@fiws/test
```
## server logs
```
http  <-- 404, user: fiws, req: 'PUT /@fiws/test', bytes: 1110/23
```

publishing packages without namespaces does work.

**Comment by maxlaverse** [comment]
Hi,
I had the same error.
My reverse-proxy (nginx) was interpreting the '%2F' as '/' and at the end the request landed on the wrong express route:
```app.put('/:package/:tag')``` instead of ```app.put('/:package/:_rev?/:revision?')```

I see you have an nginx in front of your Sinopia server. Have you tried publishing directly into Sinopia ?

Removing the trailing slash on my ```proxy_pass directive``` solved my problems:
```proxy_pass``` http://npm/;
to
```proxy_pass``` http://npm;

Can you try this ?

**Comment by fiws** [comment]
@maxlaverse thanks a lot, this solved the problem. 
Maybe this should be in the readme..?
