### ISSUE TITLE
Node v0.12.0 Uncaught Exception

### ISSUE THREAD

**Issue by kooliokey** [rlidwka/sinopia#212]
Hello, when I try to install an npm package (from the public registry) through sinopia, I get the following error and the server shuts down:

```
fatal --- uncaught exception, please report this
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at module.exports (/usr/local/lib/node_modules/sinopia/node_modules/crypt3/index.js:24:9)
    at Object.verify_password (/usr/local/lib/node_modules/sinopia/node_modules/sinopia-htpasswd/utils.js:93:12)
    at /usr/local/lib/node_modules/sinopia/node_modules/sinopia-htpasswd/index.js:39:16
    at /usr/local/lib/node_modules/sinopia/node_modules/sinopia-htpasswd/index.js:113:9
    at FSReqWrap.oncomplete (fs.js:99:15)
```

Also, when I start sinopia I get the following notices:

```
[Error: Module did not self-register.]
{ [Error: Cannot find module './build/default/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/Debug/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
```

I just updated my node.js to v0.12.0 from 0.10.\* and it was working fine before, so it is something that changed in v0.12.0.

Key

**Comment by rlidwka** [comment]
You are trying to use module compiled against node 0.10 with node 0.12.

Please run `npm rebuild` to recompile it.
