### ISSUE TITLE
Receiving randomly connection refused

### ISSUE THREAD

**Issue by Z3roCoder** [rlidwka/sinopia#233]
I have installed Sinopia and let it run as a Windows Service via nssm.exe
Now I have sometimes the problem that I receive an Error like this:

npm ERR! Error: connect ECONNREFUSED
npm ERR!     at errnoException (net.js:904:11)
npm ERR!     at Object.afterConnect [as oncomplete] (net.js:895:19)
npm ERR!  { [Error: connect ECONNREFUSED]
npm ERR!   code: 'ECONNREFUSED',
npm ERR!   errno: 'ECONNREFUSED',
npm ERR!   syscall: 'connect',
npm ERR!   parent: 'Folder' }
npm ERR! 
npm ERR! If you are behind a proxy, please make sure that the
npm ERR! 'proxy' config is set properly.  See: 'npm help config'

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "c:\\build\\nodejs.bin\\\\node.exe" "c:\\build\\nodejs.bin\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd c:\build\workspace
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! syscall connect
npm ERR! code ECONNREFUSED
npm ERR! errno ECONNREFUSED
npm ERR! stack Error: connect ECONNREFUSED
npm ERR! stack     at errnoException (net.js:904:11)
npm ERR! stack     at Object.afterConnect [as oncomplete] (net.js:895:19)

And I have absolutely no Idea why I am getting this, because publishing or installing packages worked minutes ago just perfectly fine.
And there is nothing shown about this in NPM logs either so I can not provide you any logged information. Does anyone have an Idea what might be causing this?

**Comment by Z3roCoder** [comment]
And when I run "npm install *packagename*" a few times and get that error, then wait for a few minutes and run the command again it works perfectly fine! What is up with that?

**Comment by INTCOO** [comment]
I am also facing similar issue. Any fix?

**Comment by pranay-mathur** [comment]
I am also facing similar issue. Any fix?
