### ISSUE TITLE
Fatal error while installing packages

### ISSUE THREAD

**Issue by Aaike** [rlidwka/sinopia#265]
I get this when i try to run a `npm install` in my project

```
fatal --- uncaught exception, please report this
Error: not implemented
    at Readable._read (/home/aaike/.npm-packages/lib/node_modules/sinopia/node_modules/readable-stream/lib/_stream_readable.js:496:22)
    at Readable.read (/home/aaike/.npm-packages/lib/node_modules/sinopia/node_modules/readable-stream/lib/_stream_readable.js:373:10)
    at Readable.resume (/home/aaike/.npm-packages/lib/node_modules/sinopia/node_modules/readable-stream/lib/_stream_readable.js:742:12)
    at Readable.on (/home/aaike/.npm-packages/lib/node_modules/sinopia/node_modules/readable-stream/lib/_stream_readable.js:708:10)
    at Storage.get_url (/home/aaike/.npm-packages/lib/node_modules/sinopia/lib/up-storage.js:313:11)
    at on_open (/home/aaike/.npm-packages/lib/node_modules/sinopia/lib/storage.js:252:29)
    at UploadTarball.<anonymous> (/home/aaike/.npm-packages/lib/node_modules/sinopia/lib/storage.js:271:7)
    at UploadTarball.emit (events.js:104:17)
    at UploadTarball.<anonymous> (/home/aaike/.npm-packages/lib/node_modules/sinopia/lib/local-storage.js:399:12)
    at UploadTarball.emit (events.js:104:17)
```

**Comment by Aaike** [comment]
i also frequently get a `warn  --> host registry.npmjs.org is now offline`
followed by a bunch of `ETIMEDOUT` errors

**Comment by Aaike** [comment]
ok this just turned out to be an actual issue with my internet connection ... sorry about that ;)

**Comment by ptitgraig** [comment]
Someone should close this issue.

**Comment by warsonzhou** [comment]
@Aaike why do you say that it is because of your network connection issue? Can you tell me detail about that? Thanks a lot!
