### ISSUE TITLE
Uncaught exception when enabling file logging

### ISSUE THREAD

**Issue by dizzib** [rlidwka/sinopia#272]
Uncaught exception after adding this line to config:

    - {type: file, path: /var/log/sinopia.log, level: info}

sinopia 1.4.0
node 0.10.35

    [andy@tesla script]$ cat /home/andy/.config/sinopia.yaml
    # path to a directory with all packages                                                               
    storage: /mnt/global/var/cache/sinopia/storage                                                        
                                                                                                          
    # a list of users                                                                                     
    #                                                                                                     
    # This could be deprecated soon, use "users_file" instead.                                            
    users:                                                                                                
      admin:                                                                                              
        # crypto.createHash('sha1').update(pass).digest('hex')                                            
        password: e604305dee761176967235f0d4aff03450099b4e                                                
                                                                                                          
    web:                                                                                                  
      # web interface is disabled by default in 0.x, will be enabled soon in 1.x                          
      # when all its issues will be fixed
      #
      # set this to `true` if you want to experiment with web ui now;
      # this has a lot of issues, e.g. no auth yet, so use at your own risk
      enable: true

      title: Sinopia
      # logo: logo.png

    auth:
      htpasswd:
        file: ./htpasswd
        # Maximum amount of users allowed to register, defaults to "+inf".
        # You can set this to 0 to disable registration.
        #max_users: 1000

    # a list of other known repositories we can talk to
    uplinks:
      npmjs:
        url: https://registry.npmjs.org/

        # amount of time to wait for repository to respond
        # before giving up and use the local cached copy
        #timeout: 30s

        # maximum time in which data is considered up to date
        #
        # default is 2 minutes, so server won't request the same data from
        # uplink if a similar request was made less than 2 minutes ago
        #maxage: 2m

        # if two subsequent requests fail, no further requests will be sent to
        # this uplink for five minutes
        #max_fails: 2
        #fail_timeout: 5m

        # timeouts are defined in the same way as nginx, see:
        # http://wiki.nginx.org/ConfigNotation

    packages:
      # uncomment this for packages with "local-" prefix to be available
      # for admin only, it's a recommended way of handling private packages
      #'local-*':
      #  allow_access: admin
      #  allow_publish: admin
      #  # you can override storage directory for a group of packages this way:
      #  storage: 'local_storage'

      '*':
        # allow all users to read packages (including non-authenticated users)
        #
        # you can specify usernames/groupnames (depending on your auth plugin)
        # and three keywords: "$all", "$anonymous", "$authenticated"
        allow_access: $all

        # allow 'admin' to publish packages
        #allow_publish: admin
        allow_publish: andy

        # if package is not available locally, proxy requests to 'npmjs' registry
        proxy: npmjs

    #####################################################################
    # Advanced settings
    #####################################################################

    # if you use nginx with custom path, use this to override links
    #url_prefix: https://dev.company.local/sinopia/

    # you can specify listen address (or simply a port)
    #listen: localhost:4873
    listen: 192.168.56.1:4873

    # type: file | stdout | stderr
    # level: trace | debug | info | http (default) | warn | error | fatal
    #
    # parameters for file: name is filename
    #  {type: 'file', path: 'sinopia.log', level: 'debug'},
    #
    # parameters for stdout and stderr: format: json | pretty
    #  {type: 'stdout', format: 'pretty', level: 'debug'},
    logs:
      - {type: stdout, format: pretty, level: http}
      - {type: file, path: /var/log/sinopia.log, level: info}

    # you can specify proxy used with all requests in wget-like manner here
    # (or set up ENV variables with the same name)
    #http_proxy: http://something.local/
    #https_proxy: https://something.local/
    #no_proxy: localhost,127.0.0.1

    # maximum size of uploaded json document
    # increase it if you have "request entity too large" errors
    #max_body_size: 1mb

    # Workaround for countless npm bugs. Must have for npm <1.14.x, but expect
    # it to be turned off in future versions. If `true`, latest tag is ignored,
    # and the highest semver is placed instead.
    #ignore_latest_tag: false

Uncaught exception...

    [andy@tesla script]$ sinopia -c /home/andy/.config/sinopia.yaml
     warn  --- config file  - /home/andy/.config/sinopia.yaml
     warn  --- http address - http://192.168.56.1:4873/
     fatal --- uncaught exception, please report this
    TypeError: Object function Logger(options, _childOptions, _childSimple) {
        xxx('Logger start:', options)
        if (!(this instanceof Logger)) {
            return new Logger(options, _childOptions);
        }

        // Input arg validation.
        var parent;
        if (_childOptions !== undefined) {
            parent = options;
            options = _childOptions;
            if (!(parent instanceof Logger)) {
                throw new TypeError(
                    'invalid Logger creation: do not pass a second arg');
            }
        }
        if (!options) {
            throw new TypeError('options (object) is required');
        }
        if (!parent) {
            if (!options.name) {
                throw new TypeError('options.name (string) is required');
            }
        } else {
            if (options.name) {
                throw new TypeError(
                    'invalid options.name: child cannot set logger name');
            }
        }
        if (options.stream && options.streams) {
            throw new TypeError('cannot mix "streams" and "stream" options');
        }
        if (options.streams && !Array.isArray(options.streams)) {
            throw new TypeError('invalid options.streams: must be an array')
        }
        if (options.serializers && (typeof (options.serializers) !== 'object' ||
                Array.isArray(options.serializers))) {
            throw new TypeError('invalid options.serializers: must be an object')
        }

        EventEmitter.call(this);

        // Fast path for simple child creation.
        if (parent && _childSimple) {
            // `_isSimpleChild` is a signal to stream close handling that this child
            // owns none of its streams.
            this._isSimpleChild = true;

            this._level = parent._level;
            this.streams = parent.streams;
            this.serializers = parent.serializers;
            this.src = parent.src;
            var fields = this.fields = {};
            var parentFieldNames = Object.keys(parent.fields);
            for (var i = 0; i < parentFieldNames.length; i++) {
                var name = parentFieldNames[i];
                fields[name] = parent.fields[name];
            }
            var names = Object.keys(options);
            for (var i = 0; i < names.length; i++) {
                var name = names[i];
                fields[name] = options[name];
            }
            return;
        }

        // Null values.
        var self = this;
        if (parent) {
            this._level = parent._level;
            this.streams = [];
            for (var i = 0; i < parent.streams.length; i++) {
                var s = objCopy(parent.streams[i]);
                s.closeOnExit = false; // Don't own parent stream.
                this.streams.push(s);
            }
            this.serializers = objCopy(parent.serializers);
            this.src = parent.src;
            this.fields = objCopy(parent.fields);
            if (options.level) {
                this.level(options.level);
            }
        } else {
            this._level = Number.POSITIVE_INFINITY;
            this.streams = [];
            this.serializers = null;
            this.src = false;
            this.fields = {};
        }

        if (!dtp && dtrace) {
            dtp = dtrace.createDTraceProvider('bunyan');

            for (var level in levelFromName) {
                var probe;

                probes[levelFromName[level]] = probe =
                    dtp.addProbe('log-' + level, 'char *');

                // Explicitly add a reference to dtp to prevent it from being GC'd
                probe.dtp = dtp;
            }

            dtp.enable();
        }

        // Handle *config* options (i.e. options that are not just plain data
        // for log records).
        if (options.stream) {
            self.addStream({
                type: 'stream',
                stream: options.stream,
                closeOnExit: false,
                level: options.level
            });
        } else if (options.streams) {
            options.streams.forEach(function (s) {
                self.addStream(s, options.level);
            });
        } else if (parent && options.level) {
            this.level(options.level);
        } else if (!parent) {
            if (isBrowser) {
                /*
                 * In the browser we'll be emitting to console.log by default.
                 * Any console.log worth its salt these days can nicely render
                 * and introspect objects (e.g. the Firefox and Chrome console)
                 * so let's emit the raw log record. Are there browsers for which
                 * that breaks things?
                 */
                self.addStream({
                    type: 'raw',
                    stream: new ConsoleRawStream(),
                    closeOnExit: false,
                    level: options.level
                });
            } else {
                self.addStream({
                    type: 'stream',
                    stream: process.stdout,
                    closeOnExit: false,
                    level: options.level
                });
            }
        }
        if (options.serializers) {
            self.addSerializers(options.serializers);
        }
        if (options.src) {
            this.src = true;
        }
        xxx('Logger: ', self)

        // Fields.
        // These are the default fields for log records (minus the attributes
        // removed in this constructor). To allow storing raw log records
        // (unrendered), `this.fields` must never be mutated. Create a copy for
        // any changes.
        var fields = objCopy(options);
        delete fields.stream;
        delete fields.level;
        delete fields.streams;
        delete fields.serializers;
        delete fields.src;
        if (this.serializers) {
            this._applySerializers(fields);
        }
        if (!fields.hostname) {
            fields.hostname = os.hostname();
        }
        if (!fields.pid) {
            fields.pid = process.pid;
        }
        Object.keys(fields).forEach(function (k) {
            self.fields[k] = fields[k];
        });
    } has no method 'emit'
        at WriteStream.<anonymous> (/usr/lib/node_modules/sinopia/lib/logger.js:43:16)
        at WriteStream.emit (events.js:95:17)
        at WriteStream.<anonymous> (fs.js:1669:12)
        at Object.oncomplete (fs.js:108:15)

**Comment by anitakrueger** [comment]
I'm seeing the same error. Using node v0.10.38

**Comment by anitakrueger** [comment]
Turns out there was a problem with the permissions of writing to the log file. @dizzib did you check the permissions of /var/log?
I've created /var/log/sinopia with the same user/group that I start sinopia with. That fixed it for me.
