### ISSUE TITLE
uncaught exception after running for some time

### ISSUE THREAD

**Issue by bin3** [rlidwka/sinopia#281]
node 0.12.6
sinopia 1.4.0

```
......
 http  <-- 200, user: undefined, req: 'GET /osenv', bytes: 0/2157
 http  <-- 200, user: undefined, req: 'GET /object-assign', bytes: 0/2335
 http  <-- 200, user: undefined, req: 'GET /camelcase-keys', bytes: 0/1008
 http  <-- 200, user: undefined, req: 'GET /os-tmpdir', bytes: 0/1270
 fatal --- uncaught exception, please report this
Error: not implemented
    at Readable._read (/usr/local/lib/node_modules/sinopia/node_modules/readable-stream/lib/_stream_readable.js:496:22)
    at Readable.read (/usr/local/lib/node_modules/sinopia/node_modules/readable-stream/lib/_stream_readable.js:373:10)
    at Readable.resume (/usr/local/lib/node_modules/sinopia/node_modules/readable-stream/lib/_stream_readable.js:742:12)
    at Readable.on (/usr/local/lib/node_modules/sinopia/node_modules/readable-stream/lib/_stream_readable.js:708:10)
    at Storage.get_url (/usr/local/lib/node_modules/sinopia/lib/up-storage.js:313:11)
    at on_open (/usr/local/lib/node_modules/sinopia/lib/storage.js:252:29)
    at UploadTarball.<anonymous> (/usr/local/lib/node_modules/sinopia/lib/storage.js:271:7)
    at UploadTarball.emit (events.js:104:17)
    at UploadTarball.<anonymous> (/usr/local/lib/node_modules/sinopia/lib/local-storage.js:399:12)
    at UploadTarball.emit (events.js:104:17)
```

**Comment by flexpert** [comment]
any news about this one?

**Comment by bin3** [comment]
Finally I found the reason: 
My router has been set limit on the number of connections. After turning off that limit, everything is ok.

**Comment by warsonzhou** [comment]
@bin3 You solve the problem! I want to know the details. what does the router means?
@bin3 it is urgent! Hope you reply me as soon as you can. Thanks a lot!
@flexpert Do you get what did @bin3 mean？
