### ISSUE TITLE
Error: not implemented (uncaught exception)

### ISSUE THREAD

**Issue by fpauser** [rlidwka/sinopia#282]
node: 0.12.5
sinopia: 1.4.0

````
http  <-- 200, user: undefined, req: 'GET /testem', bytes: 0/27911
 fatal --- uncaught exception, please report this
Error: not implemented
    at Readable._read (/home/fpauser/.nvm/versions/node/v0.12.5/lib/node_modules/sinopia/node_modules/readable-stream/lib/_stream_readable.js:496:22)
    at Readable.read (/home/fpauser/.nvm/versions/node/v0.12.5/lib/node_modules/sinopia/node_modules/readable-stream/lib/_stream_readable.js:373:10)
    at Readable.resume (/home/fpauser/.nvm/versions/node/v0.12.5/lib/node_modules/sinopia/node_modules/readable-stream/lib/_stream_readable.js:742:12)
    at Readable.on (/home/fpauser/.nvm/versions/node/v0.12.5/lib/node_modules/sinopia/node_modules/readable-stream/lib/_stream_readable.js:708:10)
    at Storage.get_url (/home/fpauser/.nvm/versions/node/v0.12.5/lib/node_modules/sinopia/lib/up-storage.js:313:11)
    at on_open (/home/fpauser/.nvm/versions/node/v0.12.5/lib/node_modules/sinopia/lib/storage.js:252:29)
    at UploadTarball.<anonymous> (/home/fpauser/.nvm/versions/node/v0.12.5/lib/node_modules/sinopia/lib/storage.js:271:7)
    at UploadTarball.emit (events.js:104:17)
    at UploadTarball.<anonymous> (/home/fpauser/.nvm/versions/node/v0.12.5/lib/node_modules/sinopia/lib/local-storage.js:399:12)
    at UploadTarball.emit (events.js:104:17)
````

**Comment by diegofernandes** [comment]
i`m with the same problem.

**Comment by keithallenjackson** [comment]
I have the same issue. Any insight/fixes would be very beneficial!

Node: 0.12.7
sinopia: 1.4.0
OS: Windows Server 2012 R2
installed via: npm install --global sinopia

**Comment by Zerwikapturr** [comment]
Node: v0.12.2
npm: 2.7.4
Sinopia: 1.4.0
OS: Unix RHEL6

Same issue, please advise.

**Comment by Zerwikapturr** [comment]
This doesn't look like an error with sinopia itself since after reverting to node 0.10.32 the problem is gone.

**Comment by ChrisMancini** [comment]
Same issue...

Node: v0.12.7
Sinopia: 1,4,9
OS: Linux

**Comment by stavenko** [comment]
Hello!
Just got same issue here. Made a little investigation.

How to reproduce.
1. make your registry to global npmjs.org
2. install some package1, which you never installed before and it has some dependencies on package2 that you never installed before.
3. change your registry to sinopia server.
4. reinstall you package1, but leave your package2 the same.
5. remove both package1 and package2
6. disable connection to npmjs.org from sinopia host.
7. try to install package 1 or package2.
Sinopia stores in package database `package.json` files without cache(those, that installed without sinopia help). So it unavailable to read them - tryes to connect to uplink storage - it's unavailable. Then it throws very awkward error, which doesn't helps.

**Comment by magalhas** [comment]
I'm also facing this. It's intermittent so it makes sense that it just happens where there are network problems with the upstream.
