### ISSUE TITLE
Uncaught exception

### ISSUE THREAD

**Issue by danscratch** [rlidwka/sinopia#303]
...
     http  <-- 200, user: daniel, req: 'GET /express', bytes: 0/29311
     fatal --- uncaught exception, please report this
    Error: not implemented
        at Readable._read (/usr/local/lib/node_modules/sinopia/node_modules/readable-stream/lib/_stream_readable.js:496:22)
        at Readable.read (/usr/local/lib/node_modules/sinopia/node_modules/readable-stream/lib/_stream_readable.js:373:10)
        at Readable.resume (/usr/local/lib/node_modules/sinopia/node_modules/readable-stream/lib/_stream_readable.js:742:12)
        at Readable.on (/usr/local/lib/node_modules/sinopia/node_modules/readable-stream/lib/_stream_readable.js:708:10)
        at Storage.get_url (/usr/local/lib/node_modules/sinopia/lib/up-storage.js:313:11)
        at on_open (/usr/local/lib/node_modules/sinopia/lib/storage.js:252:29)
        at UploadTarball.<anonymous> (/usr/local/lib/node_modules/sinopia/lib/storage.js:271:7)
        at UploadTarball.emit (events.js:104:17)
        at UploadTarball.<anonymous> (/usr/local/lib/node_modules/sinopia/lib/local-storage.js:399:12)
        at UploadTarball.emit (events.js:104:17)

**Comment by danscratch** [comment]
This happened during a normal run of npm install - it worked when I ran it again.

**Comment by leebenson** [comment]
I'm getting the same -- usually I can override that one error by simply running again, although subsequent runs usually generate an error in _another_ NPM package.

I have sinopia as part of a Docker Compose flow where I'm installing ~250 different packages, and it's making the workflow really unstable. It only works 50% of the time without errors. 

@rlidwka - have you investigated this?

**Comment by DanielYWoo** [comment]
I have exactly the same problem and the process exits.

**Comment by warsonzhou** [comment]
I have exactly the same problem and the process exits. Anybody know why? Sinopia always crashes.

**Comment by itcohorts** [comment]
+1, just started experiencing this error as well. Any solutions?
EDIT:
We found this was a proxy issue with the firewall we are using. When an SSL request is made for a package, but the firewall responded with an unencrypted response (blocking the request), sinopia fell over.
