### ISSUE TITLE
Problem installing Sinopia

### ISSUE THREAD

**Issue by Vj3k0** [rlidwka/sinopia#354]
I'm trying to install Sinopia, but get some errors. I tried on Node 5.2.0, 5.1.0 and Node 4 LTS (all installed through brew). I also tried directly downloading and installing node from nodejs.org. No success. Here is the log:

```
/usr/local/bin/sinopia -> /usr/local/lib/node_modules/sinopia/bin/sinopia

> dtrace-provider@0.4.0 install /usr/local/lib/node_modules/sinopia/node_modules/bunyan/node_modules/dtrace-provider
> node scripts/install.js

---------------
Building dtrace-provider failed with exit code 1 and signal 0
re-run install with environment variable V set to see the build output
---------------

> crypt3@0.1.8 install /usr/local/lib/node_modules/sinopia/node_modules/crypt3
> node-gyp rebuild

  CXX(target) Release/obj.target/crypt3/crypt3.o
In file included from ../crypt3.cc:7:
../node_modules/nan/nan.h:261:25: error: redefinition of '_NanEnsureLocal'
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                        ^
../node_modules/nan/nan.h:256:25: note: previous definition is here
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Handle<T> val) {
                        ^
../node_modules/nan/nan.h:661:13: error: no member named 'smalloc' in namespace 'node'
    , node::smalloc::FreeCallback callback
      ~~~~~~^
../node_modules/nan/nan.h:672:12: error: no matching function for call to 'New'
    return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
           ^~~~~~~~~~~~~~~~~
/Users/labtiva/.node-gyp/5.2.0/include/node/node_buffer.h:31:40: note: candidate function not viable: no known conversion from 'uint32_t' (aka 'unsigned int') to
      'enum encoding' for 3rd argument
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/labtiva/.node-gyp/5.2.0/include/node/node_buffer.h:43:40: note: candidate function not viable: 2nd argument ('const char *') would lose const qualifier
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/labtiva/.node-gyp/5.2.0/include/node/node_buffer.h:28:40: note: candidate function not viable: requires 2 arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate, size_t length);
                                       ^
/Users/labtiva/.node-gyp/5.2.0/include/node/node_buffer.h:36:40: note: candidate function not viable: requires 5 arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
In file included from ../crypt3.cc:7:
../node_modules/nan/nan.h:676:12: error: no viable conversion from 'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object>'
    return node::Buffer::New(v8::Isolate::GetCurrent(), size);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/labtiva/.node-gyp/5.2.0/include/node/v8.h:210:7: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from
      'v8::MaybeLocal<v8::Object>' to 'const v8::Local<v8::Object> &' for 1st argument
class Local {
      ^
/Users/labtiva/.node-gyp/5.2.0/include/node/v8.h:210:7: note: candidate constructor (the implicit move constructor) not viable: no known conversion from
      'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object> &&' for 1st argument
class Local {
      ^
/Users/labtiva/.node-gyp/5.2.0/include/node/v8.h:214:13: note: candidate template ignored: could not match 'Local' against 'MaybeLocal'
  V8_INLINE Local(Local<S> that)
            ^
/Users/labtiva/.node-gyp/5.2.0/include/node/v8.h:326:13: note: candidate template ignored: could not match 'S *' against 'v8::MaybeLocal<v8::Object>'
  V8_INLINE Local(S* that)
            ^
In file included from ../crypt3.cc:7:
../node_modules/nan/nan.h:683:26: error: no member named 'Use' in namespace 'node::Buffer'
    return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
           ~~~~~~~~~~~~~~^
../crypt3.cc:29:30: warning: 'ErrnoException' is deprecated: Use UVException(isolate, ...) [-Wdeprecated-declarations]
                return NanThrowError(node::ErrnoException(errno, "crypt"));
                                           ^
/Users/labtiva/.node-gyp/5.2.0/include/node/node.h:100:45: note: 'ErrnoException' has been explicitly marked deprecated here
                inline v8::Local<v8::Value> ErrnoException(
                                            ^
/Users/labtiva/.node-gyp/5.2.0/include/node/node.h:66:42: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         ^
In file included from ../crypt3.cc:3:
In file included from /Users/labtiva/.node-gyp/5.2.0/include/node/node.h:42:
/Users/labtiva/.node-gyp/5.2.0/include/node/v8.h:221:5: error: assigning to 'v8::Primitive *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/labtiva/.node-gyp/5.2.0/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:414:12: note: in instantiation of function template specialization 'v8::Local<v8::Primitive>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(v8::Undefined(v8::Isolate::GetCurrent())));
           ^
../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
In file included from ../crypt3.cc:3:
In file included from /Users/labtiva/.node-gyp/5.2.0/include/node/node.h:42:
/Users/labtiva/.node-gyp/5.2.0/include/node/v8.h:221:5: error: assigning to 'v8::Boolean *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/labtiva/.node-gyp/5.2.0/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:424:12: note: in instantiation of function template specialization 'v8::Local<v8::Boolean>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(v8::True(v8::Isolate::GetCurrent())));
           ^
../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
In file included from ../crypt3.cc:3:
In file included from /Users/labtiva/.node-gyp/5.2.0/include/node/node.h:42:
/Users/labtiva/.node-gyp/5.2.0/include/node/v8.h:221:5: error: assigning to 'v8::Function *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/labtiva/.node-gyp/5.2.0/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:1514:12: note: in instantiation of function template specialization 'v8::Local<v8::Function>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(handle)->Get(kCallbackIndex)
           ^
../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
In file included from ../crypt3.cc:3:
In file included from /Users/labtiva/.node-gyp/5.2.0/include/node/node.h:42:
/Users/labtiva/.node-gyp/5.2.0/include/node/v8.h:221:5: error: assigning to 'v8::Object *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/labtiva/.node-gyp/5.2.0/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:1632:12: note: in instantiation of function template specialization 'v8::Local<v8::Object>::Local<v8::Value>' requested here
    return NanEscapeScope(handle->Get(NanNew(key)).As<v8::Object>());
           ^
../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
1 warning and 9 errors generated.
make: *** [Release/obj.target/crypt3/crypt3.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:88:13)
gyp ERR! stack     at ChildProcess.emit (events.js:173:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:201:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/Cellar/node/5.2.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/sinopia/node_modules/crypt3
gyp ERR! node -v v5.2.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm WARN install:crypt3@0.1.8 crypt3@0.1.8 install: `node-gyp rebuild`
npm WARN install:crypt3@0.1.8 Exit status 1

> fs-ext@0.4.5 install /usr/local/lib/node_modules/sinopia/node_modules/fs-ext
> node-gyp configure build

  CXX(target) Release/obj.target/fs-ext/fs-ext.o
In file included from ../fs-ext.cc:27:
../node_modules/nan/nan.h:261:25: error: redefinition of '_NanEnsureLocal'
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                        ^
../node_modules/nan/nan.h:256:25: note: previous definition is here
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Handle<T> val) {
                        ^
../node_modules/nan/nan.h:661:13: error: no member named 'smalloc' in namespace 'node'
    , node::smalloc::FreeCallback callback
      ~~~~~~^
../node_modules/nan/nan.h:672:12: error: no matching function for call to 'New'
    return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
           ^~~~~~~~~~~~~~~~~
/Users/labtiva/.node-gyp/5.2.0/include/node/node_buffer.h:31:40: note: candidate function not viable: no known conversion from 'uint32_t' (aka 'unsigned int') to
      'enum encoding' for 3rd argument
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/labtiva/.node-gyp/5.2.0/include/node/node_buffer.h:43:40: note: candidate function not viable: 2nd argument ('const char *') would lose const qualifier
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/labtiva/.node-gyp/5.2.0/include/node/node_buffer.h:28:40: note: candidate function not viable: requires 2 arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate, size_t length);
                                       ^
/Users/labtiva/.node-gyp/5.2.0/include/node/node_buffer.h:36:40: note: candidate function not viable: requires 5 arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
In file included from ../fs-ext.cc:27:
../node_modules/nan/nan.h:676:12: error: no viable conversion from 'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object>'
    return node::Buffer::New(v8::Isolate::GetCurrent(), size);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/labtiva/.node-gyp/5.2.0/include/node/v8.h:210:7: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from
      'v8::MaybeLocal<v8::Object>' to 'const v8::Local<v8::Object> &' for 1st argument
class Local {
      ^
/Users/labtiva/.node-gyp/5.2.0/include/node/v8.h:210:7: note: candidate constructor (the implicit move constructor) not viable: no known conversion from
      'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object> &&' for 1st argument
class Local {
      ^
/Users/labtiva/.node-gyp/5.2.0/include/node/v8.h:214:13: note: candidate template ignored: could not match 'Local' against 'MaybeLocal'
  V8_INLINE Local(Local<S> that)
            ^
/Users/labtiva/.node-gyp/5.2.0/include/node/v8.h:326:13: note: candidate template ignored: could not match 'S *' against 'v8::MaybeLocal<v8::Object>'
  V8_INLINE Local(S* that)
            ^
In file included from ../fs-ext.cc:27:
../node_modules/nan/nan.h:683:26: error: no member named 'Use' in namespace 'node::Buffer'
    return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
           ~~~~~~~~~~~~~~^
../fs-ext.cc:108:15: warning: 'ErrnoException' is deprecated: Use UVException(isolate, ...) [-Wdeprecated-declarations]
    argv[0] = ErrnoException(store_data->error);
              ^
/Users/labtiva/.node-gyp/5.2.0/include/node/node.h:100:45: note: 'ErrnoException' has been explicitly marked deprecated here
                inline v8::Local<v8::Value> ErrnoException(
                                            ^
/Users/labtiva/.node-gyp/5.2.0/include/node/node.h:66:42: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         ^
../fs-ext.cc:156:5: warning: 'FatalException' is deprecated: Use FatalException(isolate, ...) [-Wdeprecated-declarations]
    FatalException(try_catch);
    ^
/Users/labtiva/.node-gyp/5.2.0/include/node/node.h:283:29: note: 'FatalException' has been explicitly marked deprecated here
                inline void FatalException(const v8::TryCatch& try_catch) {
                            ^
/Users/labtiva/.node-gyp/5.2.0/include/node/node.h:66:42: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         ^
../fs-ext.cc:299:38: warning: 'ErrnoException' is deprecated: Use UVException(isolate, ...) [-Wdeprecated-declarations]
    if (i != 0) return NanThrowError(ErrnoException(errno));
                                     ^
/Users/labtiva/.node-gyp/5.2.0/include/node/node.h:100:45: note: 'ErrnoException' has been explicitly marked deprecated here
                inline v8::Local<v8::Value> ErrnoException(
                                            ^
/Users/labtiva/.node-gyp/5.2.0/include/node/node.h:66:42: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         ^
../fs-ext.cc:343:49: warning: 'ErrnoException' is deprecated: Use UVException(isolate, ...) [-Wdeprecated-declarations]
    if (offs_result == -1) return NanThrowError(ErrnoException(errno));
                                                ^
/Users/labtiva/.node-gyp/5.2.0/include/node/node.h:100:45: note: 'ErrnoException' has been explicitly marked deprecated here
                inline v8::Local<v8::Value> ErrnoException(
                                            ^
/Users/labtiva/.node-gyp/5.2.0/include/node/node.h:66:42: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         ^
../fs-ext.cc:380:44: warning: 'ErrnoException' is deprecated: Use UVException(isolate, ...) [-Wdeprecated-declarations]
    if (result == -1) return NanThrowError(ErrnoException(errno));
                                           ^
/Users/labtiva/.node-gyp/5.2.0/include/node/node.h:100:45: note: 'ErrnoException' has been explicitly marked deprecated here
                inline v8::Local<v8::Value> ErrnoException(
                                            ^
/Users/labtiva/.node-gyp/5.2.0/include/node/node.h:66:42: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         ^
../fs-ext.cc:439:40: warning: 'ErrnoException' is deprecated: Use UVException(isolate, ...) [-Wdeprecated-declarations]
    if (ret != 0) return NanThrowError(ErrnoException(errno, "utime", "", *path));
                                       ^
/Users/labtiva/.node-gyp/5.2.0/include/node/node.h:100:45: note: 'ErrnoException' has been explicitly marked deprecated here
                inline v8::Local<v8::Value> ErrnoException(
                                            ^
/Users/labtiva/.node-gyp/5.2.0/include/node/node.h:66:42: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         ^
../fs-ext.cc:476:40: warning: 'ErrnoException' is deprecated: Use UVException(isolate, ...) [-Wdeprecated-declarations]
    if (ret != 0) return NanThrowError(ErrnoException(errno, "statvfs", "", *path));
                                       ^
/Users/labtiva/.node-gyp/5.2.0/include/node/node.h:100:45: note: 'ErrnoException' has been explicitly marked deprecated here
                inline v8::Local<v8::Value> ErrnoException(
                                            ^
/Users/labtiva/.node-gyp/5.2.0/include/node/node.h:66:42: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         ^
In file included from ../fs-ext.cc:20:
In file included from /Users/labtiva/.node-gyp/5.2.0/include/node/node.h:42:
/Users/labtiva/.node-gyp/5.2.0/include/node/v8.h:221:5: error: assigning to 'v8::Primitive *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/labtiva/.node-gyp/5.2.0/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:414:12: note: in instantiation of function template specialization 'v8::Local<v8::Primitive>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(v8::Undefined(v8::Isolate::GetCurrent())));
           ^
../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
In file included from ../fs-ext.cc:20:
In file included from /Users/labtiva/.node-gyp/5.2.0/include/node/node.h:42:
/Users/labtiva/.node-gyp/5.2.0/include/node/v8.h:221:5: error: assigning to 'v8::Boolean *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/labtiva/.node-gyp/5.2.0/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:424:12: note: in instantiation of function template specialization 'v8::Local<v8::Boolean>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(v8::True(v8::Isolate::GetCurrent())));
           ^
../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
In file included from ../fs-ext.cc:20:
In file included from /Users/labtiva/.node-gyp/5.2.0/include/node/node.h:42:
/Users/labtiva/.node-gyp/5.2.0/include/node/v8.h:221:5: error: assigning to 'v8::Function *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/labtiva/.node-gyp/5.2.0/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:1514:12: note: in instantiation of function template specialization 'v8::Local<v8::Function>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(handle)->Get(kCallbackIndex)
           ^
../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
In file included from ../fs-ext.cc:20:
In file included from /Users/labtiva/.node-gyp/5.2.0/include/node/node.h:42:
/Users/labtiva/.node-gyp/5.2.0/include/node/v8.h:221:5: error: assigning to 'v8::Object *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/labtiva/.node-gyp/5.2.0/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:1632:12: note: in instantiation of function template specialization 'v8::Local<v8::Object>::Local<v8::Value>' requested here
    return NanEscapeScope(handle->Get(NanNew(key)).As<v8::Object>());
           ^
../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
7 warnings and 9 errors generated.
make: *** [Release/obj.target/fs-ext/fs-ext.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:88:13)
gyp ERR! stack     at ChildProcess.emit (events.js:173:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:201:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/Cellar/node/5.2.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /usr/local/lib/node_modules/sinopia/node_modules/fs-ext
gyp ERR! node -v v5.2.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm WARN install:fs-ext@0.4.5 fs-ext@0.4.5 install: `node-gyp configure build`
npm WARN install:fs-ext@0.4.5 Exit status 1
/usr/local/lib
└─┬ sinopia@1.4.0 
  ├── async@0.9.2 
  ├─┬ body-parser@1.12.4 
  │ ├── bytes@1.0.0 
  │ ├── content-type@1.0.1 
  │ ├─┬ debug@2.2.0 
  │ │ └── ms@0.7.1 
  │ ├── depd@1.0.1 
  │ ├── iconv-lite@0.4.8 
  │ ├─┬ on-finished@2.2.1 
  │ │ └── ee-first@1.1.0 
  │ ├── qs@2.4.2 
  │ ├─┬ raw-body@2.0.2 
  │ │ └── bytes@2.1.0 
  │ └─┬ type-is@1.6.2 
  │   ├── media-typer@0.3.0 
  │   └─┬ mime-types@2.0.12 
  │     └── mime-db@1.10.0 
  ├─┬ bunyan@1.3.5 
  │ ├─┬ dtrace-provider@0.4.0 
  │ │ └── nan@1.5.3 
  │ ├─┬ mv@2.0.3 
  │ │ ├── ncp@0.6.0 
  │ │ └── rimraf@2.2.8 
  │ └── safe-json-stringify@1.0.3 
  ├─┬ commander@2.8.1 
  │ └── graceful-readlink@1.0.1 
  ├─┬ compression@1.4.4 
  │ ├─┬ accepts@1.2.7 
  │ │ ├─┬ mime-types@2.0.12 
  │ │ │ └── mime-db@1.10.0 
  │ │ └── negotiator@0.5.3 
  │ ├── bytes@1.0.0 
  │ ├─┬ compressible@2.0.2 
  │ │ └── mime-db@1.10.0 
  │ ├─┬ debug@2.2.0 
  │ │ └── ms@0.7.1 
  │ ├── on-headers@1.0.0 
  │ └── vary@1.0.0 
  ├─┬ cookies@0.5.0 
  │ └── keygrip@1.0.1 
  ├── es6-shim@0.21.1 
  ├─┬ express@5.0.0-alpha.1 
  │ ├─┬ accepts@1.1.4 
  │ │ ├─┬ mime-types@2.0.12 
  │ │ │ └── mime-db@1.10.0 
  │ │ └── negotiator@0.4.9 
  │ ├── content-disposition@0.5.0 
  │ ├── cookie@0.1.2 
  │ ├── cookie-signature@1.0.5 
  │ ├─┬ debug@2.1.3 
  │ │ └── ms@0.7.0 
  │ ├── depd@1.0.1 
  │ ├── escape-html@1.0.1 
  │ ├─┬ etag@1.5.1 
  │ │ └── crc@3.2.1 
  │ ├── finalhandler@0.3.2 
  │ ├── fresh@0.2.4 
  │ ├── media-typer@0.3.0 
  │ ├── merge-descriptors@0.0.2 
  │ ├── methods@1.1.0 
  │ ├─┬ on-finished@2.1.1 
  │ │ └── ee-first@1.1.0 
  │ ├── parseurl@1.3.0 
  │ ├── path-to-regexp@0.1.3 
  │ ├─┬ proxy-addr@1.0.8 
  │ │ ├── forwarded@0.1.0 
  │ │ └── ipaddr.js@1.0.1 
  │ ├── qs@2.3.2 
  │ ├── range-parser@1.0.2 
  │ ├─┬ send@0.10.1 
  │ │ ├── destroy@1.0.3 
  │ │ ├── mime@1.2.11 
  │ │ └── ms@0.6.2 
  │ ├── serve-static@1.7.2 
  │ ├─┬ type-is@1.5.7 
  │ │ └─┬ mime-types@2.0.12 
  │ │   └── mime-db@1.10.0 
  │ ├── utils-merge@1.0.0 
  │ └── vary@1.0.0 
  ├─┬ express-json5@0.1.0 
  │ └─┬ raw-body@1.3.4 
  │   ├── bytes@1.0.0 
  │   └── iconv-lite@0.4.8 
  ├─┬ handlebars@2.0.0 
  │ ├─┬ optimist@0.3.7 
  │ │ └── wordwrap@0.0.3 
  │ └─┬ uglify-js@2.3.6 
  │   ├── async@0.2.10 
  │   └─┬ source-map@0.1.43 
  │     └── amdefine@0.1.0 
  ├── highlight.js@8.6.0 
  ├─┬ http-errors@1.3.1 
  │ ├── inherits@2.0.1 
  │ └── statuses@1.2.1 
  ├── jju@1.2.0 
  ├─┬ js-yaml@3.3.1 
  │ ├─┬ argparse@1.0.2 
  │ │ ├── lodash@3.9.3 
  │ │ └── sprintf-js@1.0.2 
  │ └── esprima@2.2.0 
  ├─┬ JSONStream@1.0.3 
  │ ├── jsonparse@1.0.0 
  │ └── through@2.3.7 
  ├── lunr@0.5.9 
  ├─┬ minimatch@1.0.0 
  │ ├── lru-cache@2.6.4 
  │ └── sigmund@1.0.1 
  ├─┬ mkdirp@0.5.1 
  │ └── minimist@0.0.8 
  ├─┬ readable-stream@1.1.13 
  │ ├── core-util-is@1.0.1 
  │ ├── inherits@2.0.1 
  │ ├── isarray@0.0.1 
  │ └── string_decoder@0.10.31 
  ├─┬ render-readme@1.3.0 
  │ ├─┬ markdown-it@4.2.1 
  │ │ ├─┬ argparse@1.0.2 
  │ │ │ ├── lodash@3.9.3 
  │ │ │ └── sprintf-js@1.0.2 
  │ │ ├── entities@1.1.1 
  │ │ ├── linkify-it@1.1.0 
  │ │ ├── mdurl@1.0.0 
  │ │ └── uc.micro@1.0.0 
  │ └─┬ sanitize-html@1.6.1 
  │   ├─┬ htmlparser2@3.8.2 
  │   │ ├── domelementtype@1.3.0 
  │   │ ├── domhandler@2.3.0 
  │   │ ├─┬ domutils@1.5.1 
  │   │ │ └─┬ dom-serializer@0.1.0 
  │   │ │   ├── domelementtype@1.1.3 
  │   │ │   └── entities@1.1.1 
  │   │ └── entities@1.0.0 
  │   ├── lodash@2.4.2 
  │   └── regexp-quote@0.0.0 
  ├─┬ request@2.56.0 
  │ ├── aws-sign2@0.5.0 
  │ ├─┬ bl@0.9.4 
  │ │ └─┬ readable-stream@1.0.33 
  │ │   ├── core-util-is@1.0.1 
  │ │   ├── inherits@2.0.1 
  │ │   ├── isarray@0.0.1 
  │ │   └── string_decoder@0.10.31 
  │ ├── caseless@0.10.0 
  │ ├─┬ combined-stream@1.0.3 
  │ │ └── delayed-stream@1.0.0 
  │ ├── forever-agent@0.6.1 
  │ ├─┬ form-data@0.2.0 
  │ │ └─┬ combined-stream@0.0.7 
  │ │   └── delayed-stream@0.0.5 
  │ ├─┬ har-validator@1.7.1 
  │ │ ├── bluebird@2.9.27 
  │ │ ├─┬ chalk@1.0.0 
  │ │ │ ├── ansi-styles@2.0.1 
  │ │ │ ├── escape-string-regexp@1.0.3 
  │ │ │ ├─┬ has-ansi@1.0.3 
  │ │ │ │ ├── ansi-regex@1.1.1 
  │ │ │ │ └── get-stdin@4.0.1 
  │ │ │ ├─┬ strip-ansi@2.0.1 
  │ │ │ │ └── ansi-regex@1.1.1 
  │ │ │ └── supports-color@1.3.1 
  │ │ └─┬ is-my-json-valid@2.12.0 
  │ │   ├── generate-function@2.0.0 
  │ │   ├─┬ generate-object-property@1.2.0 
  │ │   │ └── is-property@1.0.2 
  │ │   ├── jsonpointer@1.1.0 
  │ │   └── xtend@4.0.0 
  │ ├─┬ hawk@2.3.1 
  │ │ ├── boom@2.7.2 
  │ │ ├── cryptiles@2.0.4 
  │ │ ├── hoek@2.14.0 
  │ │ └── sntp@1.0.9 
  │ ├─┬ http-signature@0.11.0 
  │ │ ├── asn1@0.1.11 
  │ │ ├── assert-plus@0.1.5 
  │ │ └── ctype@0.5.3 
  │ ├── isstream@0.1.2 
  │ ├── json-stringify-safe@5.0.1 
  │ ├─┬ mime-types@2.0.12 
  │ │ └── mime-db@1.10.0 
  │ ├── node-uuid@1.4.3 
  │ ├── oauth-sign@0.8.0 
  │ ├── qs@3.1.0 
  │ ├── stringstream@0.0.4 
  │ ├── tough-cookie@1.2.0 
  │ └── tunnel-agent@0.4.0 
  ├── semver@4.3.5 
  └── sinopia-htpasswd@0.4.5 
```

Any suggestions? Thanks, cheers,
Vjeko

**Comment by abh1nav** [comment]
@Vj3k0 Just had the same problem - worked for me when I tried with v0.12.7 - so it might not have been updated to work with recent versions

**Comment by Vj3k0** [comment]
Works also with 0.12.9, while versions 4.x and 5.x are not supported. I'll close the issue because there's not much that can be done about it other than updating Sinopia.
