### ISSUE TITLE
Crashed

### ISSUE THREAD

**Issue by abienkowski** [rlidwka/sinopia#383]
Found this in my logs,

 fatal --- uncaught exception, please report this  
Error: not implemented  
    at Readable._read (/usr/lib/node_modules/sinopia/node_modules/readable-stream/lib/_stream_readable.js:496:22)
    at Readable.read (/usr/lib/node_modules/sinopia/node_modules/readable-stream/lib/_stream_readable.js:373:10) 
    at Readable.resume (/usr/lib/node_modules/sinopia/node_modules/readable-stream/lib/_stream_readable.js:742:12
    at Readable.on (/usr/lib/node_modules/sinopia/node_modules/readable-stream/lib/_stream_readable.js:708:10)  
    at Storage.get_url (/usr/lib/node_modules/sinopia/lib/up-storage.js:313:11)  
    at on_open (/usr/lib/node_modules/sinopia/lib/storage.js:252:29)  
    at UploadTarball.<anonymous> (/usr/lib/node_modules/sinopia/lib/storage.js:271:7)  
    at emitNone (events.js:67:13)  
    at UploadTarball.emit (events.js:166:7)  
    at UploadTarball.<anonymous> (/usr/lib/node_modules/sinopia/lib/local-storage.js:399:12)

**Comment by doug-wade** [comment]
My guess is someone tried to npm star / unstar a package (https://github.com/rlidwka/sinopia/blob/3f55fb4c0c6685e8b22796cce7b523bdbfb4019e/lib/index-api.js#L284).  Looks like the call is to /rewrite (https://github.com/npm/npm-registry-client/blob/06f188917bf575fe7dc7c2f6d1d4adbaa50bc423/test/star.js#L10) without any modifications by the client (https://github.com/npm/npm-registry-client/blob/06f188917bf575fe7dc7c2f6d1d4adbaa50bc423/lib/star.js)

**Comment by arch-mage** [comment]
It's reproducible. Just try to install some packages and before it's done, disconnect the internet connection. You will got that error.
