### ISSUE TITLE
Sinopia crash during npm install - "uncaught exception"

### ISSUE THREAD

**Issue by Bidthedog** [rlidwka/sinopia#402]
Hosting on a server, accessing remotely via the same domain. All are windows boxes - server is 2012 R2 Standard, client is Windows 10.

Invoked sinopia with the following command:

> sinopia --config config.yaml

Here's the full log:

```
warn  --- http address - http://0.0.0.0:8888/
 info  <-- 127.0.0.1 requested 'GET /'
 http  <-- 304, user: undefined, req: 'GET /', bytes: 0/0
 info  <-- 127.0.0.1 requested 'GET /-/static/main.css'
 info  <-- 127.0.0.1 requested 'GET /-/static/jquery.min.js'
 info  <-- 127.0.0.1 requested 'GET /-/static/main.js'
 http  <-- 304, user: undefined, req: 'GET /-/static/main.css', bytes: 0/0
 http  <-- 304, user: undefined, req: 'GET /-/static/jquery.min.js', bytes: 0/0
 http  <-- 304, user: undefined, req: 'GET /-/static/main.js', bytes: 0/0
 info  <-- 127.0.0.1 requested 'GET /-/static/fontello.eot?10872183'
 http  <-- 304, user: undefined, req: 'GET /-/static/fontello.eot?10872183', bytes: 0/0
 info  <-- 127.0.0.1 requested 'GET /-/logo'
 http  <-- 304, user: undefined, req: 'GET /-/logo', bytes: 0/0
 info  <-- 10.202.81.186 requested 'GET /momentjs'
 info  <-- 10.202.81.186 requested 'GET /reflect-metadata'
 info  <-- 10.202.81.186 requested 'GET /rxjs'
 info  <-- 10.202.81.186 requested 'GET /ng2-bootstrap'
 info  <-- 10.202.81.186 requested 'GET /systemjs'
 info  <-- 10.202.81.186 requested 'GET /concurrently'
 info  <-- 10.202.81.186 requested 'GET /zone.js'
 info  <-- 10.202.81.186 requested 'GET /glob'
 info  <-- 10.202.81.186 requested 'GET /gulp-inject'
 info  <-- 10.202.81.186 requested 'GET /gulp-remove-code'
 info  <-- 10.202.81.186 requested 'GET /gulp'
 info  <-- 10.202.81.186 requested 'GET /jasmine-core'
 info  <-- 10.202.81.186 requested 'GET /lite-server'
 info  <-- 10.202.81.186 requested 'GET /mkdirp'
 info  <-- 10.202.81.186 requested 'GET /walk'
 info  --> making request: 'GET https://registry.npmjs.org/zone.js'
 info  --> making request: 'GET https://registry.npmjs.org/gulp-remove-code'
 info  --> making request: 'GET https://registry.npmjs.org/gulp'
 info  --> making request: 'GET https://registry.npmjs.org/lite-server'
 info  --> making request: 'GET https://registry.npmjs.org/walk'
 info  <-- 10.202.81.186 requested 'GET /rimraf'
 info  <-- 10.202.81.186 requested 'GET /@angular%2fcommon'
 info  <-- 10.202.81.186 requested 'GET /systemjs-builder'
 info  <-- 10.202.81.186 requested 'GET /@angular%2fcore'
 info  <-- 10.202.81.186 requested 'GET /@angular%2fcompiler'
 info  <-- 10.202.81.186 requested 'GET /@angular%2fhttp'
 info  <-- 10.202.81.186 requested 'GET /typings'
 info  <-- 10.202.81.186 requested 'GET /@angular%2fplatform-browser'
 info  <-- 10.202.81.186 requested 'GET /@angular%2fplatform-browser-dynamic'
 info  <-- 10.202.81.186 requested 'GET /@angular%2frouter'
 info  <-- 10.202.81.186 requested 'GET /bootstrap'
 info  <-- 10.202.81.186 requested 'GET /typescript'
 info  <-- 10.202.81.186 requested 'GET /@angular%2fupgrade'
 info  <-- 10.202.81.186 requested 'GET /@angular%2frouter-deprecated'
 http  <-- 404, user: undefined, req: 'GET /@angular%2fcommon', error: no such package available
 http  <-- 404, user: undefined, req: 'GET /@angular%2fcore', error: no such package available
 http  <-- 404, user: undefined, req: 'GET /@angular%2fcompiler', error: no such package available
 http  <-- 404, user: undefined, req: 'GET /@angular%2fhttp', error: no such package available
 info  --> making request: 'GET https://registry.npmjs.org/typings'
 http  <-- 404, user: undefined, req: 'GET /@angular%2fplatform-browser', error: no such package available
 http  <-- 404, user: undefined, req: 'GET /@angular%2fplatform-browser-dynamic', error: no such package available
 http  <-- 404, user: undefined, req: 'GET /@angular%2frouter', error: no such package available
 info  --> making request: 'GET https://registry.npmjs.org/bootstrap'
 http  <-- 404, user: undefined, req: 'GET /@angular%2fupgrade', error: no such package available
 http  <-- 404, user: undefined, req: 'GET /@angular%2frouter-deprecated', error: no such package available
 info  --> making request: 'GET https://registry.npmjs.org/momentjs'
 info  --> making request: 'GET https://registry.npmjs.org/reflect-metadata'
 info  --> making request: 'GET https://registry.npmjs.org/rxjs'
 info  --> making request: 'GET https://registry.npmjs.org/ng2-bootstrap'
 info  --> making request: 'GET https://registry.npmjs.org/systemjs'
 info  --> making request: 'GET https://registry.npmjs.org/concurrently'
 info  --> making request: 'GET https://registry.npmjs.org/glob'
 info  --> making request: 'GET https://registry.npmjs.org/gulp-inject'
 info  --> making request: 'GET https://registry.npmjs.org/jasmine-core'
 info  --> making request: 'GET https://registry.npmjs.org/mkdirp'
 info  --> making request: 'GET https://registry.npmjs.org/rimraf'
 info  --> making request: 'GET https://registry.npmjs.org/systemjs-builder'
 info  --> making request: 'GET https://registry.npmjs.org/typescript'
 http  --> ERR, req: 'GET https://registry.npmjs.org/lite-server', error: read ECONNRESET
 http  <-- 404, user: undefined, req: 'GET /lite-server', error: no such package available
 http  --> ERR, req: 'GET https://registry.npmjs.org/gulp-remove-code', error: read ECONNRESET
 http  <-- 404, user: undefined, req: 'GET /gulp-remove-code', error: no such package available
 warn  --> host registry.npmjs.org is now offline
 http  --> ERR, req: 'GET https://registry.npmjs.org/momentjs', error: read ECONNRESET
 http  --> ERR, req: 'GET https://registry.npmjs.org/reflect-metadata', error: read ECONNRESET
 http  --> ERR, req: 'GET https://registry.npmjs.org/glob', error: read ECONNRESET
 http  --> ERR, req: 'GET https://registry.npmjs.org/gulp-inject', error: read ECONNRESET
 http  --> ERR, req: 'GET https://registry.npmjs.org/rimraf', error: read ECONNRESET
 http  --> ERR, req: 'GET https://registry.npmjs.org/typescript', error: read ECONNRESET
 warn  --> host registry.npmjs.org is back online
 http  <-- 304, user: undefined, req: 'GET /momentjs', bytes: 0/0
 http  <-- 304, user: undefined, req: 'GET /reflect-metadata', bytes: 0/0
 http  <-- 304, user: undefined, req: 'GET /glob', bytes: 0/0
 http  <-- 304, user: undefined, req: 'GET /gulp-inject', bytes: 0/0
 http  --> 304, req: 'GET https://registry.npmjs.org/ng2-bootstrap', bytes: 0/0
 http  --> 304, req: 'GET https://registry.npmjs.org/systemjs', bytes: 0/0
 http  --> 304, req: 'GET https://registry.npmjs.org/concurrently', bytes: 0/0
 http  --> 304, req: 'GET https://registry.npmjs.org/jasmine-core', bytes: 0/0
 http  --> 304, req: 'GET https://registry.npmjs.org/mkdirp', bytes: 0/0
 http  --> 304, req: 'GET https://registry.npmjs.org/systemjs-builder', bytes: 0/0
 http  <-- 304, user: undefined, req: 'GET /typescript', bytes: 0/0
 http  <-- 304, user: undefined, req: 'GET /rimraf', bytes: 0/0
 http  <-- 304, user: undefined, req: 'GET /ng2-bootstrap', bytes: 0/0
 http  <-- 304, user: undefined, req: 'GET /systemjs', bytes: 0/0
 http  <-- 304, user: undefined, req: 'GET /concurrently', bytes: 0/0
 http  <-- 304, user: undefined, req: 'GET /jasmine-core', bytes: 0/0
 http  <-- 304, user: undefined, req: 'GET /mkdirp', bytes: 0/0
 http  <-- 304, user: undefined, req: 'GET /systemjs-builder', bytes: 0/0
 http  --> 200, req: 'GET https://registry.npmjs.org/bootstrap', bytes: 0/31537
 http  --> 200, req: 'GET https://registry.npmjs.org/rxjs', bytes: 0/59499
 http  --> 200, req: 'GET https://registry.npmjs.org/gulp', bytes: 0/114350
 http  <-- 200, user: undefined, req: 'GET /bootstrap', bytes: 0/6100
 http  --> 200, req: 'GET https://registry.npmjs.org/typings', bytes: 0/176497
 http  <-- 200, user: undefined, req: 'GET /rxjs', bytes: 0/7741
 http  <-- 200, user: undefined, req: 'GET /gulp', bytes: 0/8464
 info  <-- 10.202.81.186 requested 'GET /rxjs/-/rxjs-5.0.0-beta.6.tgz'
 info  --> making request: 'GET https://registry.npmjs.org/rxjs/-/rxjs-5.0.0-beta.6.tgz'
 http  <-- 200, user: undefined, req: 'GET /typings', bytes: 0/12398
 http  --> 200, req: 'GET https://registry.npmjs.org/rxjs/-/rxjs-5.0.0-beta.6.tgz' (streaming)
 http  <-- 200, user: undefined, req: 'GET /rxjs/-/rxjs-5.0.0-beta.6.tgz', bytes: 0/928794
 info  <-- 10.202.81.186 requested 'GET /core-js'
 info  <-- 10.202.81.186 requested 'GET /jquery'
 info  <-- 10.202.81.186 requested 'GET /bootstrap-datepicker'
 info  <-- 10.202.81.186 requested 'GET /bootstrap-timepicker'
 info  <-- 10.202.81.186 requested 'GET /es6-shim'
 info  <-- 10.202.81.186 requested 'GET /moment'
 info  --> making request: 'GET https://registry.npmjs.org/core-js'
 info  --> making request: 'GET https://registry.npmjs.org/bootstrap-datepicker'
 info  --> making request: 'GET https://registry.npmjs.org/jquery'
 info  --> making request: 'GET https://registry.npmjs.org/bootstrap-timepicker'
 info  --> making request: 'GET https://registry.npmjs.org/es6-shim'
 info  --> making request: 'GET https://registry.npmjs.org/moment'
 http  --> ERR, req: 'GET https://registry.npmjs.org/core-js', error: read ECONNRESET
 http  <-- 404, user: undefined, req: 'GET /core-js', error: no such package available
 http  --> 304, req: 'GET https://registry.npmjs.org/moment', bytes: 0/0
 http  --> 304, req: 'GET https://registry.npmjs.org/bootstrap-timepicker', bytes: 0/0
 http  <-- 304, user: undefined, req: 'GET /moment', bytes: 0/0
 http  <-- 304, user: undefined, req: 'GET /bootstrap-timepicker', bytes: 0/0
 http  --> 200, req: 'GET https://registry.npmjs.org/jquery', bytes: 0/75296
 http  <-- 200, user: undefined, req: 'GET /jquery', bytes: 0/7597
 http  --> 200, req: 'GET https://registry.npmjs.org/bootstrap-datepicker', bytes: 0/15983
 http  <-- 200, user: undefined, req: 'GET /bootstrap-datepicker', bytes: 0/2358
 http  --> 200, req: 'GET https://registry.npmjs.org/walk', bytes: 0/24024
 http  <-- 200, user: undefined, req: 'GET /walk', bytes: 0/4649
 http  --> 200, req: 'GET https://registry.npmjs.org/es6-shim', bytes: 0/205604
 http  <-- 200, user: undefined, req: 'GET /es6-shim', bytes: 0/14890
 http  --> 200, req: 'GET https://registry.npmjs.org/zone.js', bytes: 0/69691
 http  <-- 200, user: undefined, req: 'GET /zone.js', bytes: 0/8147
 info  <-- 10.202.81.186 requested 'GET /event-stream'
 info  <-- 10.202.81.186 requested 'GET /gulp-util'
 info  --> making request: 'GET https://registry.npmjs.org/event-stream'
 info  --> making request: 'GET https://registry.npmjs.org/gulp-util'
 info  <-- 10.202.81.186 requested 'GET /bufferstreams'
 info  --> making request: 'GET https://registry.npmjs.org/bufferstreams'
 http  --> ERR, req: 'GET https://registry.npmjs.org/event-stream', error: read ECONNRESET
 http  <-- 404, user: undefined, req: 'GET /event-stream', error: no such package available
 http  --> 200, req: 'GET https://registry.npmjs.org/gulp-util', bytes: 0/62246
 http  <-- 200, user: undefined, req: 'GET /gulp-util', bytes: 0/6239
 info  <-- 10.202.81.186 requested 'GET /foreachasync'
 info  --> making request: 'GET https://registry.npmjs.org/foreachasync'
 http  --> 200, req: 'GET https://registry.npmjs.org/foreachasync', bytes: 0/7891
 http  <-- 200, user: undefined, req: 'GET /foreachasync', bytes: 0/2357
 info  <-- 10.202.81.186 requested 'GET /inherits'
 info  <-- 10.202.81.186 requested 'GET /minimatch'
 info  <-- 10.202.81.186 requested 'GET /once'
 info  <-- 10.202.81.186 requested 'GET /path-is-absolute'
 info  --> making request: 'GET https://registry.npmjs.org/inherits'
 info  --> making request: 'GET https://registry.npmjs.org/minimatch'
 info  --> making request: 'GET https://registry.npmjs.org/once'
 info  --> making request: 'GET https://registry.npmjs.org/path-is-absolute'
 http  --> ERR, req: 'GET https://registry.npmjs.org/inherits', error: read ECONNRESET
 http  <-- 404, user: undefined, req: 'GET /inherits', error: no such package available
 http  --> ERR, req: 'GET https://registry.npmjs.org/minimatch', error: read ECONNRESET
 http  <-- 404, user: undefined, req: 'GET /minimatch', error: no such package available
 warn  --> host registry.npmjs.org is now offline
 info  <-- 10.202.81.186 requested 'GET /inflight'
 http  <-- 404, user: undefined, req: 'GET /inflight', error: no such package available
 warn  --> host registry.npmjs.org is back online
 http  --> 200, req: 'GET https://registry.npmjs.org/once', bytes: 0/7542
 http  --> 200, req: 'GET https://registry.npmjs.org/path-is-absolute', bytes: 0/3205
 http  <-- 200, user: undefined, req: 'GET /once', bytes: 0/1512
 http  <-- 200, user: undefined, req: 'GET /path-is-absolute', bytes: 0/1011
 http  --> 200, req: 'GET https://registry.npmjs.org/bufferstreams', bytes: 0/12222
 http  <-- 200, user: undefined, req: 'GET /bufferstreams', bytes: 0/2780
 info  <-- 10.202.81.186 requested 'GET /bufferstreams/-/bufferstreams-1.0.1.tgz'
 info  --> making request: 'GET https://registry.npmjs.org/bufferstreams/-/bufferstreams-1.0.1.tgz'
 error --- unexpected error: read ECONNRESET
Error: read ECONNRESET
    at exports._errnoException (util.js:870:11)
    at TLSWrap.onread (net.js:552:26)
 http  <-- 500, user: undefined, req: 'GET /bufferstreams/-/bufferstreams-1.0.1.tgz', error: internal server error
 info  <-- 10.202.81.186 requested 'GET /browser-sync'
 info  <-- 10.202.81.186 requested 'GET /connect-logger'
 info  <-- 10.202.81.186 requested 'GET /lodash'
 info  --> making request: 'GET https://registry.npmjs.org/browser-sync'
 info  --> making request: 'GET https://registry.npmjs.org/connect-logger'
 info  --> making request: 'GET https://registry.npmjs.org/lodash'
 info  <-- 10.202.81.186 requested 'GET /minimist'
 info  --> making request: 'GET https://registry.npmjs.org/minimist'
 info  <-- 10.202.81.186 requested 'GET /connect-history-api-fallback'
 info  --> making request: 'GET https://registry.npmjs.org/connect-history-api-fallback'
 http  --> ERR, req: 'GET https://registry.npmjs.org/minimist', error: read ECONNRESET
 http  <-- 404, user: undefined, req: 'GET /minimist', error: no such package available
 warn  --> host registry.npmjs.org is now offline
 warn  --> host registry.npmjs.org is back online
 http  --> 200, req: 'GET https://registry.npmjs.org/lodash', bytes: 0/144091
 http  --> 200, req: 'GET https://registry.npmjs.org/connect-history-api-fallback', bytes: 0/15506
 http  <-- 200, user: undefined, req: 'GET /lodash', bytes: 0/8648
 http  <-- 200, user: undefined, req: 'GET /connect-history-api-fallback', bytes: 0/3303
 http  --> 200, req: 'GET https://registry.npmjs.org/browser-sync', bytes: 0/453045
 info  <-- 10.202.81.186 requested 'GET /arrify'
 info  <-- 10.202.81.186 requested 'GET /escape-string-regexp'
 info  <-- 10.202.81.186 requested 'GET /group-array'
 info  <-- 10.202.81.186 requested 'GET /through2'
 info  <-- 10.202.81.186 requested 'GET /stream-to-array'
 info  --> making request: 'GET https://registry.npmjs.org/arrify'
 info  --> making request: 'GET https://registry.npmjs.org/escape-string-regexp'
 info  --> making request: 'GET https://registry.npmjs.org/group-array'
 info  --> making request: 'GET https://registry.npmjs.org/through2'
 info  --> making request: 'GET https://registry.npmjs.org/stream-to-array'
 http  <-- 200, user: undefined, req: 'GET /browser-sync', bytes: 0/23786
 http  --> ERR, req: 'GET https://registry.npmjs.org/arrify', error: read ECONNRESET
 http  <-- 404, user: undefined, req: 'GET /arrify', error: no such package available
 http  --> ERR, req: 'GET https://registry.npmjs.org/stream-to-array', error: read ECONNRESET
 http  <-- 404, user: undefined, req: 'GET /stream-to-array', error: no such package available
 warn  --> host registry.npmjs.org is now offline
 warn  --> host registry.npmjs.org is back online
 http  --> 200, req: 'GET https://registry.npmjs.org/group-array', bytes: 0/11908
 http  --> 200, req: 'GET https://registry.npmjs.org/escape-string-regexp', bytes: 0/9159
 http  --> 200, req: 'GET https://registry.npmjs.org/through2', bytes: 0/39601
 http  <-- 200, user: undefined, req: 'GET /group-array', bytes: 0/2297
 http  <-- 200, user: undefined, req: 'GET /escape-string-regexp', bytes: 0/1509
 http  <-- 200, user: undefined, req: 'GET /through2', bytes: 0/5484
 http  --> 200, req: 'GET https://registry.npmjs.org/connect-logger', bytes: 0/4601
 http  <-- 200, user: undefined, req: 'GET /connect-logger', bytes: 0/1408
 info  <-- 10.202.81.186 requested 'GET /archy'
 info  <-- 10.202.81.186 requested 'GET /deprecated'
 info  <-- 10.202.81.186 requested 'GET /chalk'
 info  <-- 10.202.81.186 requested 'GET /interpret'
 info  --> making request: 'GET https://registry.npmjs.org/archy'
 info  --> making request: 'GET https://registry.npmjs.org/deprecated'
 info  --> making request: 'GET https://registry.npmjs.org/chalk'
 info  --> making request: 'GET https://registry.npmjs.org/interpret'
 info  <-- 10.202.81.186 requested 'GET /orchestrator'
 info  <-- 10.202.81.186 requested 'GET /pretty-hrtime'
 info  <-- 10.202.81.186 requested 'GET /tildify'
 info  <-- 10.202.81.186 requested 'GET /semver'
 info  <-- 10.202.81.186 requested 'GET /vinyl-fs'
 info  <-- 10.202.81.186 requested 'GET /v8flags'
 info  <-- 10.202.81.186 requested 'GET /liftoff'
 info  --> making request: 'GET https://registry.npmjs.org/orchestrator'
 info  --> making request: 'GET https://registry.npmjs.org/pretty-hrtime'
 info  --> making request: 'GET https://registry.npmjs.org/tildify'
 info  --> making request: 'GET https://registry.npmjs.org/semver'
 info  --> making request: 'GET https://registry.npmjs.org/vinyl-fs'
 info  --> making request: 'GET https://registry.npmjs.org/v8flags'
 info  --> making request: 'GET https://registry.npmjs.org/liftoff'
 http  --> ERR, req: 'GET https://registry.npmjs.org/interpret', error: read ECONNRESET
 http  <-- 404, user: undefined, req: 'GET /interpret', error: no such package available
 http  --> 200, req: 'GET https://registry.npmjs.org/archy', bytes: 0/7001
 http  --> 200, req: 'GET https://registry.npmjs.org/deprecated', bytes: 0/2116
 http  --> ERR, req: 'GET https://registry.npmjs.org/pretty-hrtime', error: read ECONNRESET
 http  <-- 404, user: undefined, req: 'GET /pretty-hrtime', error: no such package available
 http  --> ERR, req: 'GET https://registry.npmjs.org/tildify', error: read ECONNRESET
 http  <-- 404, user: undefined, req: 'GET /tildify', error: no such package available
 warn  --> host registry.npmjs.org is now offline
 http  --> 200, req: 'GET https://registry.npmjs.org/chalk', bytes: 0/31551
 warn  --> host registry.npmjs.org is back online
 http  <-- 200, user: undefined, req: 'GET /archy', bytes: 0/1785
 http  --> 200, req: 'GET https://registry.npmjs.org/orchestrator', bytes: 0/30070
 http  <-- 200, user: undefined, req: 'GET /deprecated', bytes: 0/727
 http  <-- 200, user: undefined, req: 'GET /chalk', bytes: 0/5075
 http  --> 200, req: 'GET https://registry.npmjs.org/v8flags', bytes: 0/29225
 http  --> 200, req: 'GET https://registry.npmjs.org/liftoff', bytes: 0/68262
 http  --> 200, req: 'GET https://registry.npmjs.org/vinyl-fs', bytes: 0/77681
 http  --> 200, req: 'GET https://registry.npmjs.org/semver', bytes: 0/67916
 http  <-- 200, user: undefined, req: 'GET /orchestrator', bytes: 0/5139
 info  <-- 10.202.81.186 requested 'GET /bluebird'
 info  <-- 10.202.81.186 requested 'GET /commander'
 info  <-- 10.202.81.186 requested 'GET /cross-spawn'
 info  <-- 10.202.81.186 requested 'GET /rx'
 info  --> making request: 'GET https://registry.npmjs.org/bluebird'
 info  --> making request: 'GET https://registry.npmjs.org/commander'
 info  --> making request: 'GET https://registry.npmjs.org/cross-spawn'
 info  --> making request: 'GET https://registry.npmjs.org/rx'
 http  <-- 200, user: undefined, req: 'GET /v8flags', bytes: 0/3709
 http  --> ERR, req: 'GET https://registry.npmjs.org/commander', error: read ECONNRESET
 http  <-- 404, user: undefined, req: 'GET /commander', error: no such package available
 http  <-- 200, user: undefined, req: 'GET /vinyl-fs', bytes: 0/8669
 http  <-- 200, user: undefined, req: 'GET /semver', bytes: 0/10069
 http  <-- 200, user: undefined, req: 'GET /liftoff', bytes: 0/8063
 http  --> 200, req: 'GET https://registry.npmjs.org/cross-spawn', bytes: 0/55509
 http  --> 200, req: 'GET https://registry.npmjs.org/rx', bytes: 0/173436
 info  <-- 10.202.81.186 requested 'GET /connect-logger/-/connect-logger-0.0.1.tgz'
 http  <-- 200, user: undefined, req: 'GET /cross-spawn', bytes: 0/5720
 info  --> making request: 'GET https://registry.npmjs.org/connect-logger/-/connect-logger-0.0.1.tgz'
 http  --> 200, req: 'GET https://registry.npmjs.org/bluebird', bytes: 0/370384
 error --- unexpected error: read ECONNRESET
Error: read ECONNRESET
    at exports._errnoException (util.js:870:11)
    at TLSWrap.onread (net.js:552:26)
 http  <-- 500, user: undefined, req: 'GET /connect-logger/-/connect-logger-0.0.1.tgz', error: internal server error
 http  <-- 200, user: undefined, req: 'GET /rx', bytes: 0/16488
 http  <-- 200, user: undefined, req: 'GET /bluebird', bytes: 0/21665
 info  <-- 10.202.81.186 requested 'GET /chalk/-/chalk-0.5.1.tgz'
 info  --> making request: 'GET https://registry.npmjs.org/chalk/-/chalk-0.5.1.tgz'
 warn  --> host registry.npmjs.org is now offline
 error --- unexpected error: read ECONNRESET
Error: read ECONNRESET
    at exports._errnoException (util.js:870:11)
    at TLSWrap.onread (net.js:552:26)
 http  <-- 500, user: undefined, req: 'GET /chalk/-/chalk-0.5.1.tgz', error: internal server error
 info  <-- 10.202.81.186 requested 'GET /wrappy'
 http  <-- 404, user: undefined, req: 'GET /wrappy', error: no such package available
 info  <-- 10.202.81.186 requested 'GET /rx/-/rx-2.3.24.tgz'
 fatal --- uncaught exception, please report this
Error: not implemented
    at Readable._read (C:\tools\agent_modules\node_modules\sinopia\node_modules\readable-stream\lib\_stream_readable.js:496:22)
    at Readable.read (C:\tools\agent_modules\node_modules\sinopia\node_modules\readable-stream\lib\_stream_readable.js:373:10)
    at Readable.resume (C:\tools\agent_modules\node_modules\sinopia\node_modules\readable-stream\lib\_stream_readable.js:742:12)
    at Readable.on (C:\tools\agent_modules\node_modules\sinopia\node_modules\readable-stream\lib\_stream_readable.js:708:10)
    at Storage.get_url (C:\tools\agent_modules\node_modules\sinopia\lib\up-storage.js:313:11)
    at on_open (C:\tools\agent_modules\node_modules\sinopia\lib\storage.js:252:29)
    at UploadTarball.<anonymous> (C:\tools\agent_modules\node_modules\sinopia\lib\storage.js:271:7)
    at emitNone (events.js:67:13)
    at UploadTarball.emit (events.js:166:7)
    at UploadTarball.<anonymous> (C:\tools\agent_modules\node_modules\sinopia\lib\local-storage.js:399:12)
```

And here's my config:

```
#
# This is the default config file. It allows all users to do anything,
# so don't use it on production systems.
#
# Look here for more config file examples:
# https://github.com/rlidwka/sinopia/tree/master/conf
#

# path to a directory with all packages
storage: ./.storage

auth:
  htpasswd:
    file: ./htpasswd
    # Maximum amount of users allowed to register, defaults to "+inf".
    # You can set this to -1 to disable registration.
    #max_users: 1000

# a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@*/*':
    # scoped packages
    access: $all
    publish: $authenticated

  '*':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $all

    # allow all known users to publish packages
    # (anyone can register by default, remember?)
    publish: $authenticated

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: npmjs

# log settings
logs:
  - {type: stdout, format: pretty, level: http}
  - {type: file, format: pretty, path: sinopia.log, level: info}

listen:
  - 0.0.0.0:8888
```

**Comment by suriyaa** [comment]
Read issue https://github.com/rlidwka/sinopia/issues/243.

**Comment by yaojijiayou** [comment]
i have the same problem, it seems that '/' has been escaped to '%2f'. but i don't know how to fix it..
