### ISSUE TITLE
run sinopia error

### ISSUE THREAD

**Issue by binggg** [rlidwka/sinopia#405]
```
 warn  --- config file  - /home/root1/sinopia/config.yaml
 warn  --- http address - http://0.0.0.0:4873/
 fatal --- uncaught exception, please report this
Error: /usr/local/lib/node_modules/sinopia/node_modules/crypt3/build/Release/crypt3.node: undefined symbol: _ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_6HandleIS4_EENSA_INS_9SignatureEEEi
    at Error (native)
    at Object.Module._extensions..node (module.js:440:18)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at module.exports (/usr/local/lib/node_modules/sinopia/node_modules/crypt3/index.js:24:9)
    at Object.verify_password (/usr/local/lib/node_modules/sinopia/node_modules/sinopia-htpasswd/utils.js:93:12)
    at /usr/local/lib/node_modules/sinopia/node_modules/sinopia-htpasswd/index.js:39:16
    at /usr/local/lib/node_modules/sinopia/node_modules/sinopia-htpasswd/index.js:113:9
```

**Comment by jruif** [comment]
Use this command to install sinopia : `npm install sinopia --no-optional --no-shrinkwrap`
