### ISSUE TITLE
timeout + Uncaught exception (during gulp install)

### ISSUE THREAD

**Issue by jlsjonas** [rlidwka/sinopia#407]
sinopia v.2.14.12

```
 http  <-- 200, user: jlsjonas, req: 'GET /tildify/-/tildify-1.2.0.tgz', bytes: 0/1560
 http  <-- 200, user: jlsjonas, req: 'GET /vinyl-fs/-/vinyl-fs-0.3.14.tgz', bytes: 0/4753
 http  --> 200, req: 'GET https://registry.npmjs.org/liftoff/-/liftoff-2.2.1.tgz' (streaming)
 http  <-- 200, user: jlsjonas, req: 'GET /liftoff/-/liftoff-2.2.1.tgz', bytes: 0/9349
 http  --> 304, req: 'GET https://registry.npmjs.org/ansi-styles', bytes: 0/0
 http  <-- 304, user: jlsjonas, req: 'GET /ansi-styles', bytes: 0/0
 http  --> 304, req: 'GET https://registry.npmjs.org/escape-string-regexp', bytes: 0/0
 http  <-- 304, user: jlsjonas, req: 'GET /escape-string-regexp', bytes: 0/0
 http  --> 304, req: 'GET https://registry.npmjs.org/strip-ansi', bytes: 0/0
 http  <-- 304, user: jlsjonas, req: 'GET /strip-ansi', bytes: 0/0
 http  --> 304, req: 'GET https://registry.npmjs.org/has-ansi', bytes: 0/0
 http  <-- 304, user: jlsjonas, req: 'GET /has-ansi', bytes: 0/0
 http  --> 304, req: 'GET https://registry.npmjs.org/supports-color', bytes: 0/0
 http  <-- 304, user: jlsjonas, req: 'GET /supports-color', bytes: 0/0
 http  --> 304, req: 'GET https://registry.npmjs.org/ansi-regex', bytes: 0/0
 http  <-- 304, user: jlsjonas, req: 'GET /ansi-regex', bytes: 0/0
 http  --> 304, req: 'GET https://registry.npmjs.org/array-differ', bytes: 0/0
 http  --> 304, req: 'GET https://registry.npmjs.org/has-gulplog', bytes: 0/0
 http  --> 304, req: 'GET https://registry.npmjs.org/beeper', bytes: 0/0
 http  --> 200, req: 'GET https://registry.npmjs.org/array-uniq', bytes: 0/8486
 http  --> 304, req: 'GET https://registry.npmjs.org/gulplog', bytes: 0/0
 http  --> 304, req: 'GET https://registry.npmjs.org/fancy-log', bytes: 0/0
 http  --> ERR, req: 'GET https://registry.npmjs.org/lodash._reevaluate', error: ETIMEDOUT
 http  --> ERR, req: 'GET https://registry.npmjs.org/multipipe', error: ETIMEDOUT
 warn  --> host registry.npmjs.org is now offline
 warn  --> host registry.npmjs.org is back online
 http  --> 304, req: 'GET https://registry.npmjs.org/lodash._reinterpolate', bytes: 0/0
 http  --> 304, req: 'GET https://registry.npmjs.org/lodash._reescape', bytes: 0/0
 http  --> ERR, req: 'GET https://registry.npmjs.org/object-assign', error: ETIMEDOUT
 http  --> ERR, req: 'GET https://registry.npmjs.org/replace-ext', error: ETIMEDOUT
 warn  --> host registry.npmjs.org is now offline
 http  --> ERR, req: 'GET https://registry.npmjs.org/through2', error: ETIMEDOUT
 http  --> ERR, req: 'GET https://registry.npmjs.org/lodash.template', error: ESOCKETTIMEDOUT
 http  --> ERR, req: 'GET https://registry.npmjs.org/vinyl', error: ESOCKETTIMEDOUT
 http  <-- 304, user: jlsjonas, req: 'GET /array-differ', bytes: 0/0
 http  <-- 304, user: jlsjonas, req: 'GET /beeper', bytes: 0/0
 http  <-- 304, user: jlsjonas, req: 'GET /has-gulplog', bytes: 0/0
 http  <-- 304, user: jlsjonas, req: 'GET /gulplog', bytes: 0/0
 http  <-- 304, user: jlsjonas, req: 'GET /lodash._reevaluate', bytes: 0/0
 http  <-- 304, user: jlsjonas, req: 'GET /fancy-log', bytes: 0/0
 http  <-- 304, user: jlsjonas, req: 'GET /multipipe', bytes: 0/0
 http  <-- 304, user: jlsjonas, req: 'GET /lodash._reinterpolate', bytes: 0/0
 http  <-- 304, user: jlsjonas, req: 'GET /lodash._reescape', bytes: 0/0
 http  <-- 304, user: jlsjonas, req: 'GET /replace-ext', bytes: 0/0
 http  <-- 304, user: jlsjonas, req: 'GET /object-assign', bytes: 0/0
 http  <-- 304, user: jlsjonas, req: 'GET /through2', bytes: 0/0
 http  <-- 304, user: jlsjonas, req: 'GET /vinyl', bytes: 0/0
 http  --> 200, req: 'GET https://registry.npmjs.org/dateformat', bytes: 0/19419
 http  <-- 200, user: jlsjonas, req: 'GET /lodash.template', bytes: 0/4120
 http  <-- 200, user: jlsjonas, req: 'GET /array-uniq', bytes: 0/1595
 http  <-- 200, user: jlsjonas, req: 'GET /dateformat', bytes: 0/2937
 fatal --- uncaught exception, please report this
Error: not implemented
    at Readable._read (/usr/local/lib/node_modules/sinopia/node_modules/readable-stream/lib/_stream_readable.js:496:22)
    at Readable.read (/usr/local/lib/node_modules/sinopia/node_modules/readable-stream/lib/_stream_readable.js:373:10)
    at Readable.resume (/usr/local/lib/node_modules/sinopia/node_modules/readable-stream/lib/_stream_readable.js:742:12)
    at Readable.on (/usr/local/lib/node_modules/sinopia/node_modules/readable-stream/lib/_stream_readable.js:708:10)
    at Storage.get_url (/usr/local/lib/node_modules/sinopia/lib/up-storage.js:313:11)
    at on_open (/usr/local/lib/node_modules/sinopia/lib/storage.js:252:29)
    at UploadTarball.<anonymous> (/usr/local/lib/node_modules/sinopia/lib/storage.js:271:7)
    at emitNone (events.js:67:13)
    at UploadTarball.emit (events.js:166:7)
    at UploadTarball.<anonymous> (/usr/local/lib/node_modules/sinopia/lib/local-storage.js:399:12)
```

**Comment by geekx63** [comment]
I modify the maximum number of connections to solve this problem。In linux default maximum number of connections is 1024。
`# ulimit -n`
`1024`
`# ulimit -n 1048576`
`# ulimit -n`
`1048576`
This setting is only temporary and require root privileges。
You can put this configuration persistent，Setting Method ask google。

**Comment by warsonzhou** [comment]
@geekx63 I have change ulimit to 999999, but it always crashes as usual. Have you solved it? @jlsjonas   And you? Thanks a lot!

**Comment by mabukar** [comment]
The same crash happens for me as well, any solution for this issue?

**Comment by jlsjonas** [comment]
I'll check again this weekend @zhougch5
either way ...that shouldn't cause a crash, but make it take longer.

**Comment by warsonzhou** [comment]
@jlsjonas Have you solved the problem?
