### ISSUE TITLE
Sinopia crashes and report 443, ENOTFOUND and not implemented error!

### ISSUE THREAD

**Issue by warsonzhou** [rlidwka/sinopia#410]
@rlidwka I put sinopia running in the  docker which runs on ubuntu, it is stable for a long time, but recently it is used by increasing people, and it always crashes. I has review the issues post before. They all point that the#  **ulimit** is too small, and i modified ulimit to make it larger(i made ulimit to 999999) successfully. But sinopia always crashes as before. It report error as follows. Could someone answer my question? Thanks a lot!!

http  --> ERR, req: 'GET https://registry.npmjs.org/sass', error: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
 http  <-- 200, user: chenpy, req: 'GET /sass', bytes: 0/701
 http  --> ERR, req: 'GET https://registry.npmjs.org/karma-ng-html2js-preprocessor', error: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
 http  --> ERR, req: 'GET https://registry.npmjs.org/karma-coverage', error: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
 warn  --> host registry.npmjs.org is now offline
 http  --> ERR, req: 'GET https://registry.npmjs.org/karma-angular-filesort', error: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
 http  --> ERR, req: 'GET https://registry.npmjs.org/karma-phantomjs-lau

 http  <-- 200, user: undefined, req: 'GET /-/static/favicon.png', bytes: 0/315
 http  --> ERR, req: 'GET https://registry.npmjs.org/gfc-core', error: ETIMEDOUT

Error: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
    at errnoException (dns.js:26:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete](dns.js:77:26)

http  --> ERR, req: 'GET https://registry.npmjs.org/gulp-htmlmin', error: connect ECONNREFUSED 103.245.222.162:443
 http  <-- 200, user: hanyaonian, req: 'GET /gulp-htmlmin', bytes: 0/3473
 http  --> ERR, req: 'GET https://registry.npmjs.org/del', error: connect ECONNREFUSED 103.245.222.162:443
 http  --> ERR, req: 'GET https://registry.npmjs.org/gulp-flatten', error: connect ECONNREFUSED 103.245.222.162:443
 http  --> ERR, req: 'GET https://registry.npmjs.org/gulp-livescript', error: connect ECONNREFUSED 103.245.222.162:443

Error: not implemented
    at Readable._read (/opt/sinopia/node_modules/sinopia/node_modules/readable-stream/lib/_stream_readable.js:496:22)
    at Readable.read (/opt/sinopia/node_modules/sinopia/node_modules/readable-stream/lib/_stream_readable.js:373:10)
    at Readable.resume (/opt/sinopia/node_modules/sinopia/node_modules/readable-stream/lib/_stream_readable.js:742:12)
    at Readable.on (/opt/sinopia/node_modules/sinopia/node_modules/readable-stream/lib/_stream_readable.js:708:10)
    at Storage.get_url (/opt/sinopia/node_modules/sinopia/lib/up-storage.js:313:11)
    at on_open (/opt/sinopia/node_modules/sinopia/lib/storage.js:252:29)

Error: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
    at errnoException (dns.js:26:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete](dns.js:77:26)
 http  <-- 500, user: chenzl25, req: 'GET /plugin-error/-/plugin-error-0.1.2.tgz', error: internal server error
 warn  --> host registry.npmjs.org is now offline
 error --- unexpected error: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443

**Comment by neuoy** [comment]
I also get this error (same callstack): when sinopia can't connect to npmjs.org for some reason, and I request a package that is not stored by sinopia, it will crash. This is a bit annoying because:

- the `npm install` command that requested the package keeps running seemingly forever, and doesn't display anything about the error, so it might take time to understand sinopia just crashed
- the sinopia server has to be restarted manually

I think it should instead send an error that would be displayed in the command line that requested for the unavailable package (explaining the package might exist, but sinopia can't contact npmjs.org at this time), and continue serving future requests. Actually, maybe a well placed try/catch block could avoid any crash at all (i.e. not limited to the issue discussed here), and instead respond 500 errors or something?
