### ISSUE TITLE
npm adduser is error!!!Probably because crypt3

### ISSUE THREAD

**Issue by lengziyu** [rlidwka/sinopia#433]
backgroud:
My boss ask me to build a good internal NPM in half a month.I use `sinopia` Various error,I not much time,I thinks I'm going to lose my job.Who can Help me.
linux
node v4.6.1
npm 2.15.9
```
#npm adduser --registry http://localhost:4873
```
```
Username: (username) chenguangda
Password: 
Email: (this IS public) 1058566903@qq.com
npm ERR! Linux 2.6.32-131.0.15.el6.x86_64
npm ERR! argv "/opt/nodejs/node-v4.6.1-linux-x64/bin/node" "/usr/local/bin/npm" "adduser" "--registry" "http://localhost:4873"
npm ERR! node v4.6.1
npm ERR! npm  v2.15.9
npm ERR! code E500

npm ERR! internal server error : -/user/org.couchdb.user:chenguangda
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm-debug.log
```

**Comment by lengziyu** [comment]
The message:

```
[root@MAP-B-win2008R2sta-WEB-cheshi ~]# sinopia
Sinopia doesn't need superuser privileges. Don't run it under root.
 warn  --- config file  - /root/sinopia/config.yaml
 warn  --- http address - http://localhost:4873/
{ _id: 'org.couchdb.user:chenguangda',
  name: 'chenguangda',
  password: 'c212223',
  email: '1058566903@qq.com',
  type: 'user',
  roles: [],
  date: '2016-11-08T08:34:40.772Z' }
 error --- unexpected error: Cannot find module './build/Release/crypt3'
Error: Cannot find module './build/Release/crypt3'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at module.exports (/opt/sinopia/sinopia-1.4.0/node_modules/sinopia-htpasswd/node_modules/crypt3/index.js:24:9)
    at Object.add_user_to_htpasswd (/opt/sinopia/sinopia-1.4.0/node_modules/sinopia-htpasswd/utils.js:107:14)
    at /opt/sinopia/sinopia-1.4.0/node_modules/sinopia-htpasswd/index.js:93:20
    at callback (/opt/sinopia/sinopia-1.4.0/node_modules/sinopia-htpasswd/utils.js:55:19)
    at /opt/sinopia/sinopia-1.4.0/node_modules/sinopia-htpasswd/utils.js:59:21
    at /opt/sinopia/sinopia-1.4.0/node_modules/sinopia-htpasswd/utils.js:23:21
 http  <-- 500, user: undefined, req: 'PUT /-/user/org.couchdb.user:chenguangda', error: internal server error
```

**Comment by lengziyu** [comment]
Solved

**Comment by lengziyu** [comment]
#

**Comment by wufeng87** [comment]
Please tell us how u solved this problem?
Thanks a lot.

update, use verdaccio instead. :)

**Comment by lengziyu** [comment]
@wufeng87 hello, And you use windows?
I found **crypt3** module is not compatible with Windows system.
See,this is my run on Linux server, use sinopia pm2 management process.
![image](https://raw.githubusercontent.com/lengziyu/noteBook/master/neibunpm.png)
To ensure that all modules installed complete, depend on the module is a little more, better network. I wish you good luck.

**Comment by small-carbon** [comment]
@lengziyu For help
