### ISSUE TITLE
[help wanted] Installation issue on Linux

### ISSUE THREAD

**Issue by keerthivasan-r** [rlidwka/sinopia#461]
Hi, I am trying to setup sinopia in a Linux machine. I am getting build errors in node-gyp module. Please see the below stack trace

```
   ^
make: *** [Release/obj.target/fs-ext/fs-ext.o] Error 1
make: Leaving directory `/usr/local/lib/node_modules/sinopia/node_modules/fs-ext/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 3.10.0-514.26.2.el7.x86_64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /usr/local/lib/node_modules/sinopia/node_modules/fs-ext
gyp ERR! node -v v7.2.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

```

**Comment by keerthivasan-r** [comment]
I fixed it by installing with `npm install sinopia --no-optional ----no-shrinkwrap`
