### ISSUE TITLE
npm adduser ERR! code E500

### ISSUE THREAD

**Issue by cybermerlin** [rlidwka/sinopia#470]
on server
```

 error --- unexpected error: Cannot find module './build/Release/crypt3'
Error: Cannot find module './build/Release/crypt3'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at module.exports (/usr/local/lib/node_modules/sinopia/node_modules/crypt3/index.js:24:9)
    at Object.add_user_to_htpasswd (/usr/local/lib/node_modules/sinopia/node_modules/sinopia-htpasswd/utils.js:107:14)
    at /usr/local/lib/node_modules/sinopia/node_modules/sinopia-htpasswd/index.js:93:20
    at callback (/usr/local/lib/node_modules/sinopia/node_modules/sinopia-htpasswd/utils.js:55:19)
    at /usr/local/lib/node_modules/sinopia/node_modules/sinopia-htpasswd/utils.js:59:21
    at /usr/local/lib/node_modules/sinopia/node_modules/sinopia-htpasswd/utils.js:23:21
 http  <-- 500, user: undefined, req: 'PUT /-/user/org.couchdb.user:cybermerlin', error: internal server error
```

**Comment by cybermerlin** [comment]
[console.log](https://github.com/rlidwka/sinopia/files/1523842/console.log)

**Comment by Tony1952466760** [comment]
I have the problem too.
My solution:
 npm i -g sinopia-for-htpasswd
cd /root/.config/sinopia
touch htpasswd
sinopia-adduser

here input your username and password.

In the client：
npm login

**Comment by cybermerlin** [comment]
Thanks. That helped me.

**Comment by kingStart** [comment]
404 Not Found: sinopia-for-htpasswd@latest

**Comment by kingStart** [comment]
I resoved it throuth htpasswd-for-sinopia

$ npm install htpasswd-for-sinopia -g
$ sinopia-adduser
