### ISSUE TITLE
uncaught exception, please report this

### ISSUE THREAD

**Issue by mh-alahdadian** [rlidwka/sinopia#485]
I am using your library in my network to prevent from downloading files more than one(using your cache system)
today after I requested for an `npm install` the program has stopped and this error has been logged.

```
 fatal --- uncaught exception, please report this
Error: not implemented
    at Readable._read (C:\Users\Administrator\AppData\Roaming\npm\node_modules\sinopia\node_modules\readable-stream\lib\_
stream_readable.js:496:22)
    at Readable.read (C:\Users\Administrator\AppData\Roaming\npm\node_modules\sinopia\node_modules\readable-stream\lib\_s
tream_readable.js:373:10)
    at Readable.resume (C:\Users\Administrator\AppData\Roaming\npm\node_modules\sinopia\node_modules\readable-stream\lib\
_stream_readable.js:742:12)
    at Readable.on (C:\Users\Administrator\AppData\Roaming\npm\node_modules\sinopia\node_modules\readable-stream\lib\_str
eam_readable.js:708:10)
    at Storage.get_url (C:\Users\Administrator\AppData\Roaming\npm\node_modules\sinopia\lib\up-storage.js:315:11)
    at on_open (C:\Users\Administrator\AppData\Roaming\npm\node_modules\sinopia\lib\storage.js:252:29)
    at PassThrough.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\sinopia\lib\storage.js:271:7)
    at emitNone (events.js:105:13)
    at PassThrough.emit (events.js:207:7)
    at PassThrough.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\sinopia\lib\local-storage.js:399:
12)
```

I had start program again and again after my request it has been stopped again
thanks for your library

**Comment by jmwilkinson** [comment]
Support on this project was discontinued. A forked project, [verdaccio](https://www.verdaccio.org/), was created to continue development. You may want to switch to it.

**Comment by mh-alahdadian** [comment]
Thanks
but why it's not mentioned in readme file? it's an important thing

**Comment by juanpicado** [comment]
@MHA15 because the author does not want to merge https://github.com/rlidwka/sinopia/pull/448 and this drive to confusions to many users as you unfortunately
